<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.10.18" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

<meta name="author" content="Carlos Daniel Urresty" />
<meta name="dcterms.date" content="2026-07-27" />

<title>Reporte tecnico - Trabajo 01 – Trabajo Carlos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">Trabajo Carlos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Inicioo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/numerica.html"> 
<span class="menu-text">Numerica</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/combinatoria.html"> 
<span class="menu-text">Combinatoria</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/conclusiones.qmd"> 
<span class="menu-text">Conclusiones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/prompts.html"> 
<span class="menu-text">Uso de IA</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn"
      data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" 
      aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
      onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <h1 class="quarto-secondary-nav-title no-breadcrumbs"></h1>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" role="link"
        aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
        onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduccion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/numerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimización Numérica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/combinatoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimización combinatoria</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/reporte_tecnico.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Reporte tecnico - Trabajo 01</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="/prompts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parte 4: Uso de Inteligencia Artificial en el Proyecto</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" ></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <div id="quarto-toc-target"></div>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reporte tecnico - Trabajo 01</h1>
<p class="subtitle lead">Optimizacion numerica y combinatoria</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Carlos Daniel Urresty </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Nacional de Colombia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estructura-del-blog" id="toc-estructura-del-blog"><span class="header-section-number">1</span> Estructura del Blog</a>
  <ul>
  <li><a href="#introduccion" id="toc-introduccion"><span class="header-section-number">1.1</span> Introduccion</a></li>
  <li><a href="#secciones-principales" id="toc-secciones-principales"><span class="header-section-number">1.2</span> Secciones principales</a></li>
  </ul></li>
  <li><a href="#parte-1-optimización-numérica" id="toc-parte-1-optimización-numérica"><span class="header-section-number">2</span> Parte 1: Optimización Numérica</a>
  <ul>
  <li><a href="#funciones-de-prueba" id="toc-funciones-de-prueba"><span class="header-section-number">2.1</span> Funciones de prueba</a>
  <ul>
  <li><a href="#función-de-rosenbrock" id="toc-función-de-rosenbrock"><span class="header-section-number">2.1.1</span> Función de Rosenbrock</a></li>
  <li><a href="#función-de-rastrigin" id="toc-función-de-rastrigin"><span class="header-section-number">2.1.2</span> Función de Rastrigin</a></li>
  <li><a href="#función-de-schwefel" id="toc-función-de-schwefel"><span class="header-section-number">2.1.3</span> Función de Schwefel</a></li>
  <li><a href="#función-de-griewank" id="toc-función-de-griewank"><span class="header-section-number">2.1.4</span> Función de Griewank</a></li>
  <li><a href="#función-de-goldstein-price" id="toc-función-de-goldstein-price"><span class="header-section-number">2.1.5</span> Función de Goldstein-Price</a></li>
  <li><a href="#función-six-hump-camel" id="toc-función-six-hump-camel"><span class="header-section-number">2.1.6</span> Función Six-Hump Camel</a></li>
  <li><a href="#gráficos-de-superficie-y-contorno" id="toc-gráficos-de-superficie-y-contorno"><span class="header-section-number">2.1.7</span> Gráficos de superficie y contorno</a></li>
  </ul></li>
  <li><a href="#optimización-con-descenso-por-gradiente" id="toc-optimización-con-descenso-por-gradiente"><span class="header-section-number">2.2</span> Optimización con Descenso por Gradiente</a>
  <ul>
  <li><a href="#metodología" id="toc-metodología"><span class="header-section-number">2.2.1</span> Metodología</a></li>
  <li><a href="#visualización-de-la-función-objetivo" id="toc-visualización-de-la-función-objetivo"><span class="header-section-number">2.2.2</span> Visualización de la función objetivo</a></li>
  <li><a href="#tabla-resumen-de-desempeño" id="toc-tabla-resumen-de-desempeño"><span class="header-section-number">2.2.3</span> Tabla resumen de desempeño</a></li>
  <li><a href="#histogramas-de-valor-final" id="toc-histogramas-de-valor-final"><span class="header-section-number">2.2.4</span> Histogramas de valor final</a></li>
  <li><a href="#histogramas-de-evaluaciones" id="toc-histogramas-de-evaluaciones"><span class="header-section-number">2.2.5</span> Histogramas de evaluaciones</a></li>
  <li><a href="#conclusión-parcial" id="toc-conclusión-parcial"><span class="header-section-number">2.2.6</span> Conclusión Parcial</a></li>
  </ul></li>
  <li><a href="#optimización-con-métodos-heurísticos" id="toc-optimización-con-métodos-heurísticos"><span class="header-section-number">2.3</span> Optimización con Métodos Heurísticos</a>
  <ul>
  <li><a href="#metodología-1" id="toc-metodología-1"><span class="header-section-number">2.3.1</span> Metodología</a></li>
  <li><a href="#parámetros-de-los-algoritmos" id="toc-parámetros-de-los-algoritmos"><span class="header-section-number">2.3.2</span> Parámetros de los algoritmos</a></li>
  <li><a href="#tablas-de-resumen-comparativo" id="toc-tablas-de-resumen-comparativo"><span class="header-section-number">2.3.3</span> Tablas de resumen comparativo</a></li>
  <li><a href="#comparación-gráfica-de-desempeño" id="toc-comparación-gráfica-de-desempeño"><span class="header-section-number">2.3.4</span> Comparación gráfica de desempeño</a></li>
  <li><a href="#comparación-gráfica-de-la-mediana-del-valor-final" id="toc-comparación-gráfica-de-la-mediana-del-valor-final"><span class="header-section-number">2.3.5</span> Comparación gráfica de la mediana del valor final</a></li>
  <li><a href="#convergencia-por-función" id="toc-convergencia-por-función"><span class="header-section-number">2.3.6</span> Convergencia por función</a></li>
  </ul></li>
  <li><a href="#comparación-final-entre-métodos" id="toc-comparación-final-entre-métodos"><span class="header-section-number">2.4</span> Comparación final entre métodos</a>
  <ul>
  <li><a href="#tabla-comparativa-global" id="toc-tabla-comparativa-global"><span class="header-section-number">2.4.1</span> Tabla comparativa global</a></li>
  <li><a href="#conteo-global-de-victorias" id="toc-conteo-global-de-victorias"><span class="header-section-number">2.4.2</span> Conteo global de victorias</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones"><span class="header-section-number">2.4.3</span> Conclusiones</a></li>
  <li><a href="#animación-representativa-del-método-ganador" id="toc-animación-representativa-del-método-ganador"><span class="header-section-number">2.4.4</span> Animación representativa del método ganador</a></li>
  <li><a href="#fuente-de-datos" id="toc-fuente-de-datos"><span class="header-section-number">2.4.5</span> Fuente de datos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#parte-2-optimización-combinatoria-tsp---96-departamentos-de-francia" id="toc-parte-2-optimización-combinatoria-tsp---96-departamentos-de-francia"><span class="header-section-number">3</span> Parte 2: Optimización Combinatoria (TSP - 96 Departamentos de Francia)</a>
  <ul>
  <li><a href="#descripción-del-problema" id="toc-descripción-del-problema"><span class="header-section-number">3.1</span> 3.1 Descripción del problema</a></li>
  <li><a href="#construcción-y-preprocesamiento-de-datos" id="toc-construcción-y-preprocesamiento-de-datos"><span class="header-section-number">3.2</span> 3.2 Construcción y preprocesamiento de datos</a></li>
  <li><a href="#algoritmos-utilizados" id="toc-algoritmos-utilizados"><span class="header-section-number">3.3</span> 3.3 Algoritmos utilizados</a>
  <ul>
  <li><a href="#algoritmos-genéticos-ga" id="toc-algoritmos-genéticos-ga"><span class="header-section-number">3.3.1</span> Algoritmos Genéticos (GA)</a></li>
  </ul></li>
  <li><a href="#configuración-final-de-parámetros-para-el-algoritmo-genético" id="toc-configuración-final-de-parámetros-para-el-algoritmo-genético"><span class="header-section-number">3.4</span> Configuración final de parámetros para el algoritmo genético</a></li>
  <li><a href="#resultados" id="toc-resultados"><span class="header-section-number">3.5</span> 3.4 Resultados</a></li>
  <li><a href="#visualización" id="toc-visualización"><span class="header-section-number">3.6</span> 3.5 Visualización</a>
  <ul>
  <li><a href="#comparación-visual-de-costos" id="toc-comparación-visual-de-costos"><span class="header-section-number">3.6.1</span> Comparación visual de costos</a></li>
  <li><a href="#gif-del-mejor-recorrido-en-francia" id="toc-gif-del-mejor-recorrido-en-francia"><span class="header-section-number">3.6.2</span> GIF del mejor recorrido en Francia</a></li>
  <li><a href="#curva-de-convergencia-del-método-ganador" id="toc-curva-de-convergencia-del-método-ganador"><span class="header-section-number">3.6.3</span> Curva de convergencia del método ganador</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusiones-y-aprendizajes" id="toc-conclusiones-y-aprendizajes"><span class="header-section-number">4</span> Conclusiones y Aprendizajes</a>
  <ul>
  <li><a href="#conclusiones-generales" id="toc-conclusiones-generales"><span class="header-section-number">4.1</span> Conclusiones generales</a></li>
  <li><a href="#aprendizajes-metodológicos" id="toc-aprendizajes-metodológicos"><span class="header-section-number">4.2</span> Aprendizajes metodológicos</a></li>
  </ul></li>
  <li><a href="#parte-4-uso-de-inteligencia-artificial-en-el-proyecto" id="toc-parte-4-uso-de-inteligencia-artificial-en-el-proyecto"><span class="header-section-number">5</span> Parte 4: Uso de Inteligencia Artificial en el Proyecto</a>
  <ul>
  <li><a href="#prompts-principales-utilizados" id="toc-prompts-principales-utilizados"><span class="header-section-number">5.1</span> 4.1 Prompts principales utilizados</a>
  <ul>
  <li><a href="#prompt-1-diseno-de-experimentos-para-aco-y-ga" id="toc-prompt-1-diseno-de-experimentos-para-aco-y-ga"><span class="header-section-number">5.1.1</span> Prompt 1: diseno de experimentos para ACO y GA</a></li>
  <li><a href="#prompt-2-interpretacion-de-curvas-y-seleccion-de-configuracion-final" id="toc-prompt-2-interpretacion-de-curvas-y-seleccion-de-configuracion-final"><span class="header-section-number">5.1.2</span> Prompt 2: interpretacion de curvas y seleccion de configuracion final</a></li>
  <li><a href="#prompt-3-visualizacion-de-la-mejor-ruta-sobre-el-mapa-de-francia" id="toc-prompt-3-visualizacion-de-la-mejor-ruta-sobre-el-mapa-de-francia"><span class="header-section-number">5.1.3</span> Prompt 3: visualizacion de la mejor ruta sobre el mapa de Francia</a></li>
  <li><a href="#prompt-4-integracion-de-tablas-figuras-y-texto-en-el-reporte-tecnico" id="toc-prompt-4-integracion-de-tablas-figuras-y-texto-en-el-reporte-tecnico"><span class="header-section-number">5.1.4</span> Prompt 4: integracion de tablas, figuras y texto en el reporte tecnico</a></li>
  <li><a href="#prompt-5-organizacion-e-interpretacion-de-resultados-en-optimizacion-numerica" id="toc-prompt-5-organizacion-e-interpretacion-de-resultados-en-optimizacion-numerica"><span class="header-section-number">5.1.5</span> Prompt 5: organizacion e interpretacion de resultados en optimizacion numerica</a></li>
  <li><a href="#prompt-6-redaccion-de-introducciones-metodologia-y-cierre" id="toc-prompt-6-redaccion-de-introducciones-metodologia-y-cierre"><span class="header-section-number">5.1.6</span> Prompt 6: redaccion de introducciones, metodologia y cierre</a></li>
  </ul></li>
  <li><a href="#impacto-global-de-la-ia-en-el-proyecto" id="toc-impacto-global-de-la-ia-en-el-proyecto"><span class="header-section-number">5.2</span> 4.2 Impacto global de la IA en el proyecto</a></li>
  </ul></li>
  </ul>
</nav>
<!--

---
title: "Optimización combinatoria"
bibliography: referencias.bib
---

-->
<section id="estructura-del-blog" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Estructura del Blog</h1>
<section id="introduccion" class="level2" data-number="1.1">
<h2 data-number="1.1"><span class="header-section-number">1.1</span> Introduccion</h2>
<p>Este blog presenta el desarrollo del trabajo con una estructura pensada para explicar de forma clara tanto el planteamiento como los resultados obtenidos. El objetivo principal es mostrar, de manera organizada, como se abordaron dos problemas de optimizacion con naturalezas distintas, permitiendo comparar estrategias y extraer conclusiones utiles a partir de la experiencia. Por un lado, se trabaja la <strong>Optimizacion Numerica</strong>, centrada en el analisis de funciones y en la aplicacion de metodos de descenso por gradiente para encontrar soluciones eficientes. Por otro lado, se desarrolla la <strong>Optimizacion Combinatoria</strong>, enfocada en el problema del viajante aplicado al recorrido de los 96 departamentos de Francia, un caso mucho mas complejo por la enorme cantidad de combinaciones posibles.</p>
<p>La comparacion entre ambos enfoques resulta importante porque permite entender como cambian las herramientas segun la naturaleza del problema: mientras los metodos basados en gradiente aprovechan informacion analitica de la funcion, los algoritmos heurísticos y metaheuristicos buscan buenas soluciones en espacios discretos donde no siempre es posible aplicar metodos exactos de manera practica. En conjunto, el trabajo deja como aprendizaje principal que no existe una unica estrategia universal de optimizacion, sino que la eleccion del metodo depende del tipo de problema, del costo computacional y de la calidad de solucion que se desea alcanzar.</p>
<p>Para la parte combinatoria, la construccion del conjunto de datos de ciudades y trayectos requirio una etapa previa de extraccion de informacion. Esta se realizo mediante <strong>web scraping</strong> sobre el sitio <a href="https://www.vinci-autoroutes.com/fr/mon-trajet/">VINCI Autoroutes</a>, a partir del cual se obtuvieron los datos necesarios para estructurar la instancia trabajada en el problema del viajante. El script utilizado para este procedimiento hace parte del proyecto y se incluye como soporte tecnico del proceso de recoleccion y preparacion de datos en el archivo <a href="../2.%20optimizacion_combinatoria/docs/scraping/web_scrapping.js">web_scrapping.js</a>.</p>
</section>
<section id="secciones-principales" class="level2" data-number="1.2">
<h2 data-number="1.2"><span class="header-section-number">1.2</span> Secciones principales</h2>
<ul>
<li><a href="./numerica.qmd">Optimizacion numerica</a></li>
<li><a href="./combinatoria.qmd">Optimizacion combinatoria</a></li>
</ul>
<p>En particular, una parte importante del codigo, la organizacion tecnica del proyecto y el ensamblaje del reporte fueron realizados por Carlos, quien retomo lo ya avanzado, completo componentes faltantes y estructuro la version final presentada en este blog. Por tanto, la contribucion individual principal corresponde a Carlos, tanto en la programacion como en la consolidacion del trabajo entregado.</p>
</section>
</section>
<section id="parte-1-optimización-numérica" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Parte 1: Optimización Numérica</h1>
<section id="funciones-de-prueba" class="level2" data-number="2.1">
<h2 data-number="2.1"><span class="header-section-number">2.1</span> Funciones de prueba</h2>
<p>Para evaluar el comportamiento de los métodos de optimización numérica, se seleccionaron varias funciones de prueba ampliamente utilizadas en la literatura. En conjunto, estas funciones benchmark ofrecen paisajes de optimización con propiedades diversas, como multimodalidad, distintos niveles de separabilidad y valles estrechos, por lo que constituyen una base adecuada para comparar la convergencia y la robustez de distintos algoritmos frente a problemas de diferente dificultad <span class="citation" data-cites="jamil2013">(<a href="#ref-jamil2013" role="doc-biblioref">Jamil and Yang 2013</a>)</span>.</p>
<section id="función-de-rosenbrock" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1"><span class="header-section-number">2.1.1</span> Función de Rosenbrock</h3>
<p>La función de Rosenbrock es un caso clásico en optimización continua. Su principal dificultad es la presencia de un valle largo, curvo y angosto que conduce al mínimo global. Aunque la función no es extremadamente multimodal, muchos algoritmos tienen dificultades para avanzar de manera estable dentro de este valle y acercarse con precisión a la solución.</p>
<p><span class="math display">\[
f(x, y) = (1 - x)^2 + 100(y - x^2)^2
\]</span></p>
<p>Su mínimo global se encuentra en <span class="math inline">\((1,1)\)</span>, donde <span class="math inline">\(f(x,y)=0\)</span>.</p>
</section>
<section id="función-de-rastrigin" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2"><span class="header-section-number">2.1.2</span> Función de Rastrigin</h3>
<p>La función de Rastrigin es ampliamente usada para evaluar algoritmos en escenarios multimodales. Su superficie contiene una gran cantidad de mínimos locales distribuidos periódicamente, lo que dificulta la búsqueda del mínimo global. Por esta razón, resulta muy útil para analizar la capacidad de exploración de un método de optimización.</p>
<p><span class="math display">\[
f(\mathbf{x}) = 10n + \sum_{i=1}^{n} \left(x_i^2 - 10 \cos(2\pi x_i)\right)
\]</span></p>
<p>Su mínimo global se encuentra en <span class="math inline">\(\mathbf{x}=\mathbf{0}\)</span>, donde <span class="math inline">\(f(\mathbf{x})=0\)</span>.</p>
</section>
<section id="función-de-schwefel" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3"><span class="header-section-number">2.1.3</span> Función de Schwefel</h3>
<p>La función de Schwefel representa un reto importante debido a que su mínimo global está alejado del origen y la superficie presenta muchas irregularidades. Esto obliga a los algoritmos a explorar con cuidado el dominio de búsqueda y evita que una estrategia demasiado local encuentre con facilidad la mejor solución.</p>
<p><span class="math display">\[
f(\mathbf{x}) = 418.9829\,n - \sum_{i=1}^{n} x_i \sin\left(\sqrt{|x_i|}\right)
\]</span></p>
<p>Su mínimo global se alcanza aproximadamente cuando <span class="math inline">\(x_i = 420.9687\)</span> para todo <span class="math inline">\(i\)</span>.</p>
</section>
<section id="función-de-griewank" class="level3" data-number="2.1.4">
<h3 data-number="2.1.4"><span class="header-section-number">2.1.4</span> Función de Griewank</h3>
<p>La función de Griewank combina un crecimiento cuadrático moderado con un componente oscilatorio multiplicativo. Esta estructura genera varios mínimos locales, aunque de una forma menos agresiva que en Rastrigin. Por ello, es útil para estudiar el comportamiento de los algoritmos en superficies multimodales con una complejidad intermedia.</p>
<p><span class="math display">\[
f(\mathbf{x}) = 1 + \sum_{i=1}^{n}\frac{x_i^2}{4000} - \prod_{i=1}^{n}\cos\left(\frac{x_i}{\sqrt{i}}\right)
\]</span></p>
<p>Su mínimo global se encuentra en <span class="math inline">\(\mathbf{x}=\mathbf{0}\)</span>, donde <span class="math inline">\(f(\mathbf{x})=0\)</span>.</p>
</section>
<section id="función-de-goldstein-price" class="level3" data-number="2.1.5">
<h3 data-number="2.1.5"><span class="header-section-number">2.1.5</span> Función de Goldstein-Price</h3>
<p>La función de Goldstein-Price es una función bidimensional con una superficie compleja y altamente irregular. Presenta cambios pronunciados en la curvatura y varias zonas que pueden desviar la trayectoria de búsqueda, por lo que es adecuada para evaluar la precisión y estabilidad de los algoritmos en problemas no triviales.</p>
<p><span class="math display">\[
\begin{aligned}
f(x,y) &amp;= \left[1 + (x+y+1)^2(19 - 14x + 3x^2 - 14y + 6xy + 3y^2)\right] \\
&amp;\quad \cdot \left[30 + (2x-3y)^2(18 - 32x + 12x^2 + 48y - 36xy + 27y^2)\right]
\end{aligned}
\]</span></p>
<p>Su mínimo global se encuentra en <span class="math inline">\((0,-1)\)</span>, donde el valor de la función es <span class="math inline">\(3\)</span>.</p>
</section>
<section id="función-six-hump-camel" class="level3" data-number="2.1.6">
<h3 data-number="2.1.6"><span class="header-section-number">2.1.6</span> Función Six-Hump Camel</h3>
<p>La función Six-Hump Camel es otro ejemplo clásico en dos dimensiones. Su interés principal radica en que posee varios puntos críticos y dos mínimos globales simétricos. Esto permite evaluar si un algoritmo logra identificar soluciones equivalentes en distintas regiones del espacio de búsqueda.</p>
<p><span class="math display">\[
f(x,y) = \left(4 - 2.1x^2 + \frac{x^4}{3}\right)x^2 + xy + \left(-4 + 4y^2\right)y^2
\]</span></p>
<p>Sus mínimos globales se encuentran aproximadamente en <span class="math inline">\((0.0898,-0.7126)\)</span> y <span class="math inline">\((-0.0898,0.7126)\)</span>.</p>
</section>
<section id="gráficos-de-superficie-y-contorno" class="level3" data-number="2.1.7">
<h3 data-number="2.1.7"><span class="header-section-number">2.1.7</span> Gráficos de superficie y contorno</h3>
<p>Para cada una de estas funciones se deben incluir dos tipos de visualización:</p>
<ul>
<li>un gráfico de superficie en 3D, para observar la forma general del paisaje de optimización</li>
<li>un gráfico de contorno en 2D, para identificar valles, picos, mínimos locales y zonas de mayor dificultad</li>
</ul>
<p>Estas figuras complementan la descripción matemática, ya que permiten entender visualmente por qué ciertas funciones favorecen la convergencia rápida y por qué otras representan un reto mayor para los algoritmos estudiados.</p>
</section>
</section>
<section id="optimización-con-descenso-por-gradiente" class="level2" data-number="2.2">
<h2 data-number="2.2"><span class="header-section-number">2.2</span> Optimización con Descenso por Gradiente</h2>
<p>Una vez definidas las funciones de prueba, el siguiente paso consiste en estudiar el comportamiento del descenso por gradiente sobre cada una de ellas. El descenso por gradiente es un método de optimización local que busca minimizar una función objetivo mediante actualizaciones sucesivas de la forma <span class="math display">\[
x_{k+1} = x_k - \alpha \nabla f(x_k),
\]</span> donde <span class="math inline">\(x_k\)</span> es la solución en la iteración <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha\)</span> es la tasa de aprendizaje y <span class="math inline">\(\nabla f(x_k)\)</span> es el gradiente de la función objetivo evaluado en ese punto. En cada paso, el método avanza en la dirección opuesta al gradiente para reducir el valor de la función y aproximarse a un mínimo. Aunque suele ser eficiente en funciones suaves, su desempeño depende en gran medida de la geometría de la función objetivo y de la condición inicial elegida <span class="citation" data-cites="nocedal2006">(<a href="#ref-nocedal2006" role="doc-biblioref">Nocedal and Wright 2006</a>)</span>.</p>
<section id="metodología" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1"><span class="header-section-number">2.2.1</span> Metodología</h3>
<p>Para evaluar la estabilidad del método y evitar conclusiones basadas en una sola corrida, se realizaron múltiples ejecuciones con condiciones iniciales aleatorias. En cada experimento, el algoritmo parte de un punto inicial generado dentro del dominio de la función. A partir de allí, se calcula el gradiente de la función objetivo para determinar la dirección de mayor descenso, y luego se actualiza iterativamente la solución. El criterio de parada se estableció mediante una tolerancia sobre la norma del cambio entre iteraciones, de modo que el algoritmo se detiene cuando dicho cambio es menor que 10^-6; en caso contrario, la corrida finaliza al alcanzar el número máximo de iteraciones definido para cada función.</p>
<p>El enunciado propone comparar corridas para <span class="math inline">\(n = 100\)</span>, <span class="math inline">\(500\)</span> y <span class="math inline">\(1000\)</span>. En los cuadernos de análisis se consolidaron resultados para varios casos en 2D y 3D, con énfasis en las funciones de Rosenbrock, Rastrigin, Schwefel, Griewank, Goldstein-Price y la función de las seis jorobas de camello, que pasaremos a llamar Six-Hump Camel. Además, el contenido se organizó en resúmenes por función, dimensión y número de corridas.</p>
<p>Este procedimiento permite observar no solo si el método encuentra soluciones cercanas al mínimo global, sino también con qué frecuencia lo hace, cuánta dispersión presentan los resultados finales y cuál es el costo computacional asociado.</p>
</section>
<section id="visualización-de-la-función-objetivo" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2"><span class="header-section-number">2.2.2</span> Visualización de la función objetivo</h3>
<section id="rosenbrock" class="level4" data-number="2.2.2.1">
<h4 data-number="2.2.2.1"><span class="header-section-number">2.2.2.1</span> Rosenbrock</h4>
<table class="caption-top">
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
<th style="text-align: left;">Gradiente en 3D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} -400x(y - x^2) - 2(1 - x) \\ 200(y - x^2) \end{bmatrix} \]</span></td>
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y, z) = \begin{bmatrix} -400x(y - x^2) - 2(1 - x) \\ 200(y - x^2) - 400y(z - y^2) - 2(1 - y) \\ 200(z - y^2) \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets/numerica/gradientes/images/rosenbrock/rosenbrock_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
<section id="rastrigin" class="level4" data-number="2.2.2.2">
<h4 data-number="2.2.2.2"><span class="header-section-number">2.2.2.2</span> Rastrigin</h4>
<table class="caption-top">
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
<th style="text-align: left;">Gradiente en 3D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} 2x + 20\pi \sin(2\pi x) \\ 2y + 20\pi \sin(2\pi y) \end{bmatrix} \]</span></td>
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y, z) = \begin{bmatrix} 2x + 20\pi \sin(2\pi x) \\ 2y + 20\pi \sin(2\pi y) \\ 2z + 20\pi \sin(2\pi z) \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets/numerica/gradientes/images/rastrigin/rastrigin_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
<section id="schwefel" class="level4" data-number="2.2.2.3">
<h4 data-number="2.2.2.3"><span class="header-section-number">2.2.2.3</span> Schwefel</h4>
<table class="caption-top">
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
<th style="text-align: left;">Gradiente en 3D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} -\sin\left(\sqrt{|x|}\right) - \frac{x \cos\left(\sqrt{|x|}\right)}{2\sqrt{|x|}} \\ -\sin\left(\sqrt{|y|}\right) - \frac{y \cos\left(\sqrt{|y|}\right)}{2\sqrt{|y|}} \end{bmatrix} \]</span></td>
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y, z) = \begin{bmatrix} -\sin\left(\sqrt{|x|}\right) - \frac{x \cos\left(\sqrt{|x|}\right)}{2\sqrt{|x|}} \\ -\sin\left(\sqrt{|y|}\right) - \frac{y \cos\left(\sqrt{|y|}\right)}{2\sqrt{|y|}} \\ -\sin\left(\sqrt{|z|}\right) - \frac{z \cos\left(\sqrt{|z|}\right)}{2\sqrt{|z|}} \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets/numerica/gradientes/images/schwefel/schwefel_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
<section id="griewank" class="level4" data-number="2.2.2.4">
<h4 data-number="2.2.2.4"><span class="header-section-number">2.2.2.4</span> Griewank</h4>
<table class="caption-top">
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
<th style="text-align: left;">Gradiente en 3D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} \frac{x}{2000} + \frac{1}{\sqrt{1}} \sin\left(\frac{x}{\sqrt{1}}\right) \cos\left(\frac{y}{\sqrt{2}}\right) \\ \frac{y}{2000} + \frac{1}{\sqrt{2}} \cos\left(\frac{x}{\sqrt{1}}\right) \sin\left(\frac{y}{\sqrt{2}}\right) \end{bmatrix} \]</span></td>
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y, z) = \begin{bmatrix} \frac{x}{2000} + \frac{1}{\sqrt{1}} \sin\left(\frac{x}{\sqrt{1}}\right) \cos\left(\frac{y}{\sqrt{2}}\right) \cos\left(\frac{z}{\sqrt{3}}\right) \\ \frac{y}{2000} + \frac{1}{\sqrt{2}} \cos\left(\frac{x}{\sqrt{1}}\right) \sin\left(\frac{y}{\sqrt{2}}\right) \cos\left(\frac{z}{\sqrt{3}}\right) \\ \frac{z}{2000} + \frac{1}{\sqrt{3}} \cos\left(\frac{x}{\sqrt{1}}\right) \cos\left(\frac{y}{\sqrt{2}}\right) \sin\left(\frac{z}{\sqrt{3}}\right) \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets/numerica/gradientes/images/griewank/griewank_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
<section id="goldstein-price" class="level4" data-number="2.2.2.5">
<h4 data-number="2.2.2.5"><span class="header-section-number">2.2.2.5</span> Goldstein-Price</h4>
<table class="caption-top">
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} \frac{\partial f}{\partial x} \\ \frac{\partial f}{\partial y} \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets\numerica\gradientes\images\goldstein_price\goldstein_price_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
<section id="six-hump-camel" class="level4" data-number="2.2.2.6">
<h4 data-number="2.2.2.6"><span class="header-section-number">2.2.2.6</span> Six-Hump Camel</h4>
<table class="caption-top">
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gradiente en 2D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math display">\[ \nabla f(x, y) = \begin{bmatrix} (8 - 8.4x^2 + 2x^4)x + y \\ x + (-8 + 16y^2)y \end{bmatrix} \]</span></td>
</tr>
</tbody>
</table>
<p><img src="assets/numerica/gradientes/images/six_hump_camel/six_hump_camel_mapa_calor_y_superficie.png" class="img-fluid" /></p>
</section>
</section>
<section id="tabla-resumen-de-desempeño" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3"><span class="header-section-number">2.2.3</span> Tabla resumen de desempeño</h3>
<p>A continuación se muestra el detalle específico de las funciones evaluadas en ambas dimensiones, o en una sola cuando corresponde. Esto permite observar con mayor claridad cómo cambia el desempeño del método cuando aumenta el número de corridas y cómo se distribuyen los resultados finales.</p>
<section id="rosenbrock-1" class="level4" data-number="2.2.3.1">
<h4 data-number="2.2.3.1"><span class="header-section-number">2.2.3.1</span> Rosenbrock</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.20</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.65</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.65</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">4.32</td>
<td style="text-align: right;">2.26</td>
<td style="text-align: right;">2.59</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">1002.00</td>
<td style="text-align: right;">1000.00</td>
</tr>
</tbody>
</table>
<p>Se evidencia que encuentra soluciones muy cercanas al óptimo en 2D, pero el valle estrecho y el acoplamiento en 3D dificultan ligeramente el desempeño promedio.</p>
</section>
<section id="rastrigin-1" class="level4" data-number="2.2.3.2">
<h4 data-number="2.2.3.2"><span class="header-section-number">2.2.3.2</span> Rastrigin</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">40.79</td>
<td style="text-align: right;">22.45</td>
<td style="text-align: right;">24.87</td>
<td style="text-align: right;">10.33</td>
<td style="text-align: right;">29.04</td>
<td style="text-align: right;">27.04</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">40.79</td>
<td style="text-align: right;">17.04</td>
<td style="text-align: right;">16.91</td>
<td style="text-align: right;">10.54</td>
<td style="text-align: right;">28.85</td>
<td style="text-align: right;">26.85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">40.79</td>
<td style="text-align: right;">16.48</td>
<td style="text-align: right;">16.91</td>
<td style="text-align: right;">10.58</td>
<td style="text-align: right;">29.05</td>
<td style="text-align: right;">27.05</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">58.70</td>
<td style="text-align: right;">31.95</td>
<td style="text-align: right;">35.32</td>
<td style="text-align: right;">13.04</td>
<td style="text-align: right;">30.10</td>
<td style="text-align: right;">28.10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">58.70</td>
<td style="text-align: right;">22.71</td>
<td style="text-align: right;">21.39</td>
<td style="text-align: right;">12.31</td>
<td style="text-align: right;">31.92</td>
<td style="text-align: right;">29.92</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">58.70</td>
<td style="text-align: right;">21.55</td>
<td style="text-align: right;">20.89</td>
<td style="text-align: right;">11.74</td>
<td style="text-align: right;">32.04</td>
<td style="text-align: right;">30.04</td>
</tr>
</tbody>
</table>
<p>Se observa que sufre severamente debido a sus múltiples mínimos locales; converge rápido pero se evidencia que queda atrapado casi de inmediato.</p>
</section>
<section id="schwefel-1" class="level4" data-number="2.2.3.3">
<h4 data-number="2.2.3.3"><span class="header-section-number">2.2.3.3</span> Schwefel</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">-15.32</td>
<td style="text-align: right;">985.87</td>
<td style="text-align: right;">369.84</td>
<td style="text-align: right;">416.60</td>
<td style="text-align: right;">254.49</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">-15.32</td>
<td style="text-align: right;">1225.63</td>
<td style="text-align: right;">430.81</td>
<td style="text-align: right;">401.60</td>
<td style="text-align: right;">317.57</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">-15.32</td>
<td style="text-align: right;">1225.63</td>
<td style="text-align: right;">376.59</td>
<td style="text-align: right;">341.46</td>
<td style="text-align: right;">291.55</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">-7.73</td>
<td style="text-align: right;">1203.50</td>
<td style="text-align: right;">538.47</td>
<td style="text-align: right;">542.68</td>
<td style="text-align: right;">325.66</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">-7.73</td>
<td style="text-align: right;">1450.16</td>
<td style="text-align: right;">650.61</td>
<td style="text-align: right;">660.48</td>
<td style="text-align: right;">354.56</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">-7.73</td>
<td style="text-align: right;">1450.16</td>
<td style="text-align: right;">565.92</td>
<td style="text-align: right;">517.55</td>
<td style="text-align: right;">351.71</td>
<td style="text-align: right;">10002.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
</tbody>
</table>
<p>Se denota un comportamiento muy polarizado y altamente dependiente del punto inicial; se evidencia que consume el total de las iteraciones con una desviación estándar altísima.</p>
</section>
<section id="griewank-1" class="level4" data-number="2.2.3.4">
<h4 data-number="2.2.3.4"><span class="header-section-number">2.2.3.4</span> Griewank</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1766.94</td>
<td style="text-align: right;">1764.94</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1732.03</td>
<td style="text-align: right;">1730.03</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1741.05</td>
<td style="text-align: right;">1739.05</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">2002.00</td>
<td style="text-align: right;">2000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">2002.00</td>
<td style="text-align: right;">2000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">2002.00</td>
<td style="text-align: right;">2000.00</td>
</tr>
</tbody>
</table>
<p>Se aprecia un desempeño sobresaliente y muy consistente; se demuestra que su estructura global guía con éxito al gradiente hacia valores cercanos a cero con mínima dispersión.</p>
</section>
<section id="goldstein-price-1" class="level4" data-number="2.2.3.5">
<h4 data-number="2.2.3.5"><span class="header-section-number">2.2.3.5</span> Goldstein-Price</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">10.49</td>
<td style="text-align: right;">988.65</td>
<td style="text-align: right;">148.95</td>
<td style="text-align: right;">62.27</td>
<td style="text-align: right;">264.29</td>
<td style="text-align: right;">5002.00</td>
<td style="text-align: right;">5000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">10.49</td>
<td style="text-align: right;">989.72</td>
<td style="text-align: right;">288.42</td>
<td style="text-align: right;">80.68</td>
<td style="text-align: right;">361.56</td>
<td style="text-align: right;">5002.00</td>
<td style="text-align: right;">5000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">10.49</td>
<td style="text-align: right;">989.72</td>
<td style="text-align: right;">328.08</td>
<td style="text-align: right;">81.16</td>
<td style="text-align: right;">382.52</td>
<td style="text-align: right;">5002.00</td>
<td style="text-align: right;">5000.00</td>
</tr>
</tbody>
</table>
<p>Se evidencia una alta inestabilidad y dependencia crítica del punto de partida; se observa que acierta solo si cae en la cuenca de atracción correcta, alcanzando errores cercanos a 1000.</p>
</section>
<section id="six-hump-camel-1" class="level4" data-number="2.2.3.6">
<h4 data-number="2.2.3.6"><span class="header-section-number">2.2.3.6</span> Six-Hump Camel</h4>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dimensión</th>
<th style="text-align: right;">Corridas</th>
<th style="text-align: right;">Mejor valor final</th>
<th style="text-align: right;">Peor valor final</th>
<th style="text-align: right;">Promedio del valor final</th>
<th style="text-align: right;">Mediana del valor final</th>
<th style="text-align: right;">Desv. del valor final</th>
<th style="text-align: right;">Promedio de evaluaciones</th>
<th style="text-align: right;">Promedio de iteraciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">-0.45</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">989.10</td>
<td style="text-align: right;">987.10</td>
</tr>
<tr class="even">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">996.39</td>
<td style="text-align: right;">994.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2D</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">-0.11</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">1.37</td>
<td style="text-align: right;">986.34</td>
<td style="text-align: right;">984.34</td>
</tr>
</tbody>
</table>
<p>Se constata que es muy estable y exitoso; se evidencia que su mediana se fija consistentemente en el óptimo global (<span class="math inline">\(-1.03\)</span>) a pesar de sus mínimos secundarios.</p>
</section>
</section>
<section id="histogramas-de-valor-final" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4"><span class="header-section-number">2.2.4</span> Histogramas de valor final</h3>
<p>Los histogramas del valor final permiten visualizar la distribución de las soluciones obtenidas después de todas las corridas. Esta gráfica es especialmente importante porque muestra si el algoritmo converge repetidamente hacia una misma región del espacio de soluciones o si, por el contrario, termina en distintos mínimos locales según la inicialización.</p>
<p>Cuando la mayor parte de los valores finales se concentra cerca del mínimo global, se puede interpretar que el método es relativamente estable para esa función. En cambio, cuando la distribución es amplia, sesgada o presenta varios grupos, ello sugiere que el descenso por gradiente es sensible al punto inicial o que la función contiene regiones donde la búsqueda local no logra llegar siempre a la mejor solución.</p>
<section id="rosenbrock-2" class="level4" data-number="2.2.4.1">
<h4 data-number="2.2.4.1"><span class="header-section-number">2.2.4.1</span> Rosenbrock</h4>
<section id="d" class="level5" data-number="2.2.4.1.1">
<h5 data-number="2.2.4.1.1"><span class="header-section-number">2.2.4.1.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/rosenbrock/rosenbrock_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
</section>
<section id="d-1" class="level5" data-number="2.2.4.1.2">
<h5 data-number="2.2.4.1.2"><span class="header-section-number">2.2.4.1.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/rosenbrock/rosenbrock_figura_a_histograma_solucion_final_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Rosenbrock 2D</strong>, los histogramas muestran una fuerte concentración de frecuencias en los valores cercanos a cero (especialmente a medida que aumentan las corridas <span class="math inline">\(n = 500\)</span> y <span class="math inline">\(n = 1000\)</span>), lo que evidencia que el algoritmo logra converger exitosamente en repetidas ocasiones hacia la región del óptimo global, aunque persisten algunos valores dispersos debido a la dificultad de su valle parabólico. Por otro lado, en <strong>Rosenbrock 3D</strong>, se denota que la distribución se dispersa significativamente a lo largo del eje de valores finales y aparecen múltiples grupos de frecuencias separadas; esto evidencia que el incremento dimensional amplifica la sensibilidad al punto inicial, provocando que el descenso por gradiente termine con mayor frecuencia en distintas regiones o sub-óptimos locales en lugar de consolidarse en una única zona de convergencia.</p>
</section>
</section>
<section id="rastrigin-2" class="level4" data-number="2.2.4.2">
<h4 data-number="2.2.4.2"><span class="header-section-number">2.2.4.2</span> Rastrigin</h4>
<section id="d-2" class="level5" data-number="2.2.4.2.1">
<h5 data-number="2.2.4.2.1"><span class="header-section-number">2.2.4.2.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/rastrigin/rastrigin_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
</section>
<section id="d-3" class="level5" data-number="2.2.4.2.2">
<h5 data-number="2.2.4.2.2"><span class="header-section-number">2.2.4.2.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/rastrigin/rastrigin_figura_a_histograma_solucion_final_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Rastrigin 2D</strong>, los histogramas muestran múltiples grupos de frecuencia distribuidos en diversos rangos de valores finales (con picos notables alrededor de los rangos de 0-5 y 15-20), lo que evidencia que el algoritmo es altamente sensible a la inicialización y se estanca frecuentemente en diferentes mínimos locales. Por su parte, en <strong>Rastrigin 3D</strong>, se denota que la distribución se amplía y desplaza hacia valores finales más altos, dispersando las frecuencias a lo largo de un espectro más amplio; esto evidencia que el aumento de dimensionalidad incrementa exponencialmente la cantidad de trampas multimodales, dificultando que el descenso por gradiente converja de manera consistente hacia el óptimo global.</p>
</section>
</section>
<section id="schwefel-2" class="level4" data-number="2.2.4.3">
<h4 data-number="2.2.4.3"><span class="header-section-number">2.2.4.3</span> Schwefel</h4>
<section id="d-4" class="level5" data-number="2.2.4.3.1">
<h5 data-number="2.2.4.3.1"><span class="header-section-number">2.2.4.3.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/schwefel/schwefel_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
</section>
<section id="d-5" class="level5" data-number="2.2.4.3.2">
<h5 data-number="2.2.4.3.2"><span class="header-section-number">2.2.4.3.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/schwefel/schwefel_figura_a_histograma_solucion_final_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Schwefel 2D</strong>, los histogramas muestran una dispersión muy amplia de las frecuencias a lo largo de un gran rango de valores finales (con concentraciones intermedias y altas cifras que superan los 1000), lo que evidencia que el algoritmo es sumamente inestable y depende críticamente del punto de inicialización. Por otro lado, en <strong>Schwefel 3D</strong>, se denota que la distribución se desplaza aún más hacia la derecha y amplía su dispersión alcanzando valores finales cercanos a 1400; esto evidencia que la severa complejidad de su paisaje sinusoidal y el incremento dimensional provocan que el descenso por gradiente quede atrapado de forma masiva en mínimos locales pobres en lugar de hallar el óptimo global.</p>
</section>
</section>
<section id="griewank-2" class="level4" data-number="2.2.4.4">
<h4 data-number="2.2.4.4"><span class="header-section-number">2.2.4.4</span> Griewank</h4>
<section id="d-6" class="level5" data-number="2.2.4.4.1">
<h5 data-number="2.2.4.4.1"><span class="header-section-number">2.2.4.4.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/griewank/griewank_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
</section>
<section id="d-7" class="level5" data-number="2.2.4.4.2">
<h5 data-number="2.2.4.4.2"><span class="header-section-number">2.2.4.4.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/griewank/griewank_figura_a_histograma_solucion_final_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Griewank 2D</strong>, los histogramas muestran una concentración de frecuencias muy estrecha y compacta en valores extremadamente cercanos a cero (con un rango limitado que apenas alcanza los 0.05), lo que evidencia que el algoritmo posee una excelente consistencia y estabilidad para converger repetidamente cerca del óptimo global. Por otro lado, en <strong>Griewank 3D</strong>, se denota que las frecuencias se concentran fuertemente en el primer tramo inferior cercano a cero (con picos muy altos en las corridas de <span class="math inline">\(n = 500\)</span> y <span class="math inline">\(n = 1000\)</span>), aunque con una ligera dispersión que se extiende hacia valores cercanos a 1.0; esto evidencia que, a pesar de un leve incremento en la variabilidad debido a la dimensión, la estructura global de la función permite que el descenso por gradiente mantenga una alta efectividad y robustez en la búsqueda de la solución.</p>
</section>
</section>
<section id="goldstein-price-2" class="level4" data-number="2.2.4.5">
<h4 data-number="2.2.4.5"><span class="header-section-number">2.2.4.5</span> Goldstein-Price</h4>
<section id="d-8" class="level5" data-number="2.2.4.5.1">
<h5 data-number="2.2.4.5.1"><span class="header-section-number">2.2.4.5.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/goldstein_price/goldstein_price_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Goldstein-Price 2D</strong>, los histogramas muestran una clara polarización de las frecuencias en dos extremos muy separados (con concentraciones en los valores bajos iniciales y grandes picos que rozan o alcanzan los 1000 en las corridas de <span class="math inline">\(n = 500\)</span> y <span class="math inline">\(n = 1000\)</span>); esto evidencia una alta inestabilidad y dependencia crítica del punto de partida, lo que demuestra que el descenso por gradiente solo acierta y converge con éxito si cae exactamente dentro de la cuenca de atracción correcta, terminando en mínimos locales deficientes o divergiendo cuando esto no ocurre.</p>
</section>
</section>
<section id="six-hump-camel-2" class="level4" data-number="2.2.4.6">
<h4 data-number="2.2.4.6"><span class="header-section-number">2.2.4.6</span> Six-Hump Camel</h4>
<section id="d-9" class="level5" data-number="2.2.4.6.1">
<h5 data-number="2.2.4.6.1"><span class="header-section-number">2.2.4.6.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/six_hump_camel/six_hump_camel_figura_a_histograma_solucion_final_2d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Six-Hump Camel 2D</strong>, los histogramas muestran una fuerte concentración de las frecuencias en el valor de -1.0 (el óptimo global) a lo largo de las distintas corridas (<span class="math inline">\(n = 100\)</span>, <span class="math inline">\(n = 500\)</span> y <span class="math inline">\(n = 1000\)</span>), complementada por un grupo secundario menor ubicado alrededor de 2.0; esto evidencia que el algoritmo es robusto y converge de manera mayoritaria hacia la mejor solución, a pesar de que la presencia de mínimos locales secundarios en su topología desvía ocasionalmente algunas ejecuciones hacia el otro valor final.</p>
</section>
</section>
</section>
<section id="histogramas-de-evaluaciones" class="level3" data-number="2.2.5">
<h3 data-number="2.2.5"><span class="header-section-number">2.2.5</span> Histogramas de evaluaciones</h3>
<p>Además de la calidad de la solución, es fundamental medir cuántas evaluaciones de la función objetivo fueron necesarias para alcanzar el resultado final. Para ello se emplean histogramas del número de evaluaciones, que permiten estudiar la eficiencia del método en cada caso.</p>
<p>Estos histogramas muestran si la convergencia ocurre de manera uniforme o si existen corridas mucho más costosas que otras. Una distribución concentrada en valores bajos suele indicar una convergencia más predecible y económica. En cambio, una distribución dispersa o con cola larga sugiere que algunas ejecuciones requieren muchos más pasos para estabilizarse, lo cual puede estar asociado a zonas complicadas del paisaje de optimización.</p>
<p>La interpretación conjunta entre histogramas de valor final e histogramas de evaluaciones es especialmente importante: un método puede converger rápido pero hacia soluciones pobres, o puede requerir más evaluaciones para acercarse mejor al mínimo global. Por eso, ambos indicadores deben analizarse en conjunto y no por separado.</p>
<section id="rosenbrock-3" class="level4" data-number="2.2.5.1">
<h4 data-number="2.2.5.1"><span class="header-section-number">2.2.5.1</span> Rosenbrock</h4>
<section id="d-10" class="level5" data-number="2.2.5.1.1">
<h5 data-number="2.2.5.1.1"><span class="header-section-number">2.2.5.1.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/rosenbrock/rosenbrock_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
</section>
<section id="d-11" class="level5" data-number="2.2.5.1.2">
<h5 data-number="2.2.5.1.2"><span class="header-section-number">2.2.5.1.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/rosenbrock/rosenbrock_figura_b_histograma_evaluaciones_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Rosenbrock (tanto en 2D como en 3D)</strong>, los histogramas muestran una frecuencia absoluta concentrada de manera idéntica en un único valor fijo de 1002 evaluaciones; esto evidencia un comportamiento de convergencia totalmente uniforme y predecible, indicando que el algoritmo consume siempre exactamente el mismo esfuerzo computacional para agotar o cumplir su criterio de parada sin importar el tamaño de las corridas.</p>
</section>
</section>
<section id="rastrigin-3" class="level4" data-number="2.2.5.2">
<h4 data-number="2.2.5.2"><span class="header-section-number">2.2.5.2</span> Rastrigin</h4>
<section id="d-12" class="level5" data-number="2.2.5.2.1">
<h5 data-number="2.2.5.2.1"><span class="header-section-number">2.2.5.2.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/rastrigin/rastrigin_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
</section>
<section id="d-13" class="level5" data-number="2.2.5.2.2">
<h5 data-number="2.2.5.2.2"><span class="header-section-number">2.2.5.2.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/rastrigin/rastrigin_figura_b_histograma_evaluaciones_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Rastrigin 2D y 3D</strong>, los histogramas muestran una distribución compacta y centrada de las frecuencias en un rango bajo de evaluaciones (principalmente entre 26 y 32 pasos), lo que evidencia que el algoritmo converge de manera muy rápida y predecible; sin embargo, en 3D se denota una ligera extensión hacia la derecha con frecuencias más dispersas, lo que evidencia que el aumento de dimensionalidad incrementa ligeramente el esfuerzo computacional y la variabilidad en algunas ejecuciones debido a los mínimos locales.</p>
</section>
</section>
<section id="schwefel-3" class="level4" data-number="2.2.5.3">
<h4 data-number="2.2.5.3"><span class="header-section-number">2.2.5.3</span> Schwefel</h4>
<section id="d-14" class="level5" data-number="2.2.5.3.1">
<h5 data-number="2.2.5.3.1"><span class="header-section-number">2.2.5.3.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/schwefel/schwefel_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
</section>
<section id="d-15" class="level5" data-number="2.2.5.3.2">
<h5 data-number="2.2.5.3.2"><span class="header-section-number">2.2.5.3.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/schwefel/schwefel_figura_b_histograma_evaluaciones_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Schwefel (tanto en 2D como en 3D)</strong>, los histogramas muestran una frecuencia absoluta concentrada de manera idéntica en un único valor fijo de aproximadamente 20000 evaluaciones (el tope máximo configurado); esto evidencia un comportamiento de convergencia totalmente uniforme donde el algoritmo agota por completo sus iteraciones en todas las corridas, reflejando que no logra un criterio de parada temprano debido a la complejidad de su búsqueda.</p>
</section>
</section>
<section id="griewank-3" class="level4" data-number="2.2.5.4">
<h4 data-number="2.2.5.4"><span class="header-section-number">2.2.5.4</span> Griewank</h4>
<section id="d-16" class="level5" data-number="2.2.5.4.1">
<h5 data-number="2.2.5.4.1"><span class="header-section-number">2.2.5.4.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/griewank/griewank_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
</section>
<section id="d-17" class="level5" data-number="2.2.5.4.2">
<h5 data-number="2.2.5.4.2"><span class="header-section-number">2.2.5.4.2</span> 3D</h5>
<p><img src="assets/numerica/gradientes/images/griewank/griewank_figura_b_histograma_evaluaciones_3d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Griewank 2D</strong>, los histogramas muestran una distribución dispersa de las frecuencias a lo largo de un rango amplio de evaluaciones (con un grupo notable acumulándose cerca del límite superior de 2000 pasos), lo que evidencia que el algoritmo experimenta una variabilidad considerable en su esfuerzo computacional según la inicialización. Por otro lado, en <strong>Griewank 3D</strong>, se denota que la frecuencia se concentra de manera absoluta en un único valor fijo de aproximadamente 2002 evaluaciones en todas las corridas; esto evidencia que al incrementar la dimensión, el algoritmo consume siempre el tope máximo de pasos establecidos para cumplir su convergencia, volviéndose completamente uniforme en su costo computacional.</p>
</section>
</section>
<section id="goldstein-price-3" class="level4" data-number="2.2.5.5">
<h4 data-number="2.2.5.5"><span class="header-section-number">2.2.5.5</span> Goldstein-Price</h4>
<section id="d-18" class="level5" data-number="2.2.5.5.1">
<h5 data-number="2.2.5.5.1"><span class="header-section-number">2.2.5.5.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/goldstein_price/goldstein_price_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Goldstein-Price 2D</strong>, los histogramas muestran una frecuencia absoluta concentrada en un único valor fijo de 5002 evaluaciones, lo que evidencia que el algoritmo consume siempre el tope máximo de iteraciones de manera totalmente uniforme.</p>
</section>
</section>
<section id="six-hump-camel-3" class="level4" data-number="2.2.5.6">
<h4 data-number="2.2.5.6"><span class="header-section-number">2.2.5.6</span> Six-Hump Camel</h4>
<section id="d-19" class="level5" data-number="2.2.5.6.1">
<h5 data-number="2.2.5.6.1"><span class="header-section-number">2.2.5.6.1</span> 2D</h5>
<p><img src="assets/numerica/gradientes/images/six_hump_camel/six_hump_camel_figura_b_histograma_evaluaciones_2d.png" class="img-fluid" /></p>
<p>Se observa que en <strong>Six-Hump Camel 2D</strong>, los histogramas muestran una distribución dispersa y variada de las frecuencias a lo largo de un rango amplio de evaluaciones (concentrándose principalmente entre los 800 y 1300 pasos), lo que evidencia que el algoritmo experimenta un esfuerzo computacional heterogéneo y dependiente de la ruta de búsqueda inicial para alcanzar la convergencia.</p>
</section>
</section>
</section>
<section id="conclusión-parcial" class="level3" data-number="2.2.6">
<h3 data-number="2.2.6"><span class="header-section-number">2.2.6</span> Conclusión Parcial</h3>
<p>En síntesis, el descenso por gradiente demostró ser un método eficiente y de bajo costo en términos de evaluaciones cuando se enfrenta a paisajes regulares (como Rosenbrock o zonas específicas de Griewank). Sin embargo, evidenció limitaciones severas en funciones altamente multimodales (Rastrigin y Schwefel) y superficies con valles complejos o dependencia crítica de la inicialización (Goldstein-Price), donde el algoritmo tiende a estancarse en mínimos locales deficientes o a consumir el tope máximo de iteraciones sin garantizar el óptimo global.</p>
<p>Estas limitaciones, derivadas de su naturaleza determinista y estrictamente local, justifican la transición hacia métodos heurísticos de búsqueda poblacional y estocástica, los cuales favorecen un mejor balance entre exploración y explotación del espacio de búsqueda y resultan especialmente útiles en problemas multimodales o con paisajes de optimización complejos <span class="citation" data-cites="talbi2009">(<a href="#ref-talbi2009" role="doc-biblioref">Talbi 2009</a>)</span>.</p>
</section>
</section>
<section id="optimización-con-métodos-heurísticos" class="level2" data-number="2.3">
<h2 data-number="2.3"><span class="header-section-number">2.3</span> Optimización con Métodos Heurísticos</h2>
<p>Una vez analizado el descenso por gradiente, el siguiente paso consiste en estudiar métodos de optimización heurística que no dependan de información derivativa de la función objetivo. En esta parte se emplearon tres estrategias de búsqueda poblacional: <strong>algoritmo evolutivo</strong>, <strong>optimización por enjambre de partículas (PSO)</strong> y <strong>evolución diferencial</strong>. Estos métodos resultan especialmente útiles en funciones multimodales o con paisajes complejos, donde una estrategia puramente local puede quedar atrapada en mínimos no globales.</p>
<p>El objetivo de esta subsección es comparar la calidad de las soluciones obtenidas por estos métodos, así como su costo computacional medido en número de evaluaciones de la función objetivo. De esta manera, la discusión no se centra solo en quién alcanza el mejor valor final, sino también en qué tan robusto y eficiente resulta cada enfoque frente a funciones de distinta dificultad y dimensionalidad.</p>
<section id="metodología-1" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1"><span class="header-section-number">2.3.1</span> Metodología</h3>
<p>Para el experimento heurístico se evaluaron las funciones <code>Rosenbrock</code>, <code>Rastrigin</code>, <code>Schwefel</code> y <code>Griewank</code> en <code>2D</code> y <code>3D</code>. Adicionalmente, <code>Goldstein-Price</code> y <code>Six-Hump Camel</code> se trabajaron solo en <code>2D</code>, ya que en el proyecto fueron implementadas en su formulación clásica bidimensional. En todos los casos se realizaron varias corridas con semillas distintas, registrando el mejor valor encontrado, la mejor solución, el número de iteraciones y el número de evaluaciones de la función objetivo.</p>
<p>Los resultados consolidados de esta parte fueron generados desde el bloque <code>heuristicos/</code>, utilizando una implementación unificada para los tres métodos y un criterio consistente de conteo de evaluaciones. Esto permite realizar comparaciones directas entre algoritmos bajo condiciones experimentales equivalentes.</p>
</section>
<section id="parámetros-de-los-algoritmos" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2"><span class="header-section-number">2.3.2</span> Parámetros de los algoritmos</h3>
<p>La configuración general utilizada para los experimentos heurísticos se resume a continuación, separando los parámetros de cada método para facilitar su lectura e interpretación.</p>
<section id="algoritmo-evolutivo" class="level4" data-number="2.3.2.1">
<h4 data-number="2.3.2.1"><span class="header-section-number">2.3.2.1</span> Algoritmo evolutivo</h4>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tamaño de población</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td>Fracción de elitismo</td>
<td style="text-align: right;">0.2</td>
</tr>
<tr class="odd">
<td>Fracción de mutación</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="even">
<td>Máximo de iteraciones</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</section>
<section id="pso" class="level4" data-number="2.3.2.2">
<h4 data-number="2.3.2.2"><span class="header-section-number">2.3.2.2</span> PSO</h4>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Número de partículas</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td>Peso de inercia</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="odd">
<td>Peso cognitivo</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td>Peso social</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td>Máximo de iteraciones</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</section>
<section id="evolución-diferencial" class="level4" data-number="2.3.2.3">
<h4 data-number="2.3.2.3"><span class="header-section-number">2.3.2.3</span> Evolución diferencial</h4>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tamaño de población</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td>Factor de mutación</td>
<td style="text-align: right;">0.8</td>
</tr>
<tr class="odd">
<td>Tasa de cruce</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="even">
<td>Máximo de iteraciones</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="tablas-de-resumen-comparativo" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3"><span class="header-section-number">2.3.3</span> Tablas de resumen comparativo</h3>
<p>La tabla principal de esta subsección debe consolidar, para cada función, dimensión y método, el mejor valor promedio, el mejor valor mínimo alcanzado y el promedio de evaluaciones realizadas. Esta tabla permite comparar de manera global tanto la calidad de las soluciones como el costo computacional.</p>
<p>La siguiente tabla fue construida a partir de <code>trabajo_carlos/1. optimizacion_numerica/heuristicos/datos/figuras/tabla_resumen_heuristicos.csv</code>.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Dimensión</th>
<th>Mejor método</th>
<th>Mejor valor mínimo</th>
<th>Mejor valor promedio</th>
<th>Promedio de evaluaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rosenbrock</td>
<td>2</td>
<td>Evolución diferencial</td>
<td>0.000000</td>
<td>0.000000</td>
<td>4840.0</td>
</tr>
<tr class="even">
<td>Rosenbrock</td>
<td>3</td>
<td>Evolución diferencial</td>
<td>0.000002</td>
<td>0.000242</td>
<td>4840.0</td>
</tr>
<tr class="odd">
<td>Rastrigin</td>
<td>2</td>
<td>Evolución diferencial</td>
<td>0.000000</td>
<td>0.000000</td>
<td>4840.0</td>
</tr>
<tr class="even">
<td>Rastrigin</td>
<td>3</td>
<td>Evolución diferencial</td>
<td>0.000002</td>
<td>0.038206</td>
<td>4840.0</td>
</tr>
<tr class="odd">
<td>Schwefel</td>
<td>2</td>
<td>Evolución diferencial</td>
<td>0.000025</td>
<td>0.000025</td>
<td>7050.0</td>
</tr>
<tr class="even">
<td>Schwefel</td>
<td>3</td>
<td>Evolución diferencial</td>
<td>0.000038</td>
<td>0.000038</td>
<td>7050.0</td>
</tr>
<tr class="odd">
<td>Griewank</td>
<td>2</td>
<td>PSO</td>
<td>0.000000</td>
<td>0.002583</td>
<td>7050.0</td>
</tr>
<tr class="even">
<td>Griewank</td>
<td>3</td>
<td>PSO</td>
<td>0.000000</td>
<td>0.009003</td>
<td>7050.0</td>
</tr>
<tr class="odd">
<td>Goldstein-Price</td>
<td>2</td>
<td>Evolución diferencial</td>
<td>3.000000</td>
<td>3.000000</td>
<td>4840.0</td>
</tr>
<tr class="even">
<td>Six-Hump Camel</td>
<td>2</td>
<td>PSO</td>
<td>-1.031628</td>
<td>-1.031628</td>
<td>4840.0</td>
</tr>
</tbody>
</table>
<p>En general, la tabla resume un patrón bastante claro: <code>Evolución diferencial</code> es el método más sólido en la mayoría de las funciones analizadas. En <code>Rosenbrock</code>, <code>Rastrigin</code>, <code>Schwefel</code> y <code>Goldstein-Price</code>, este método alcanza los mejores valores promedio y, al mismo tiempo, mantiene un costo computacional estable, lo que sugiere una buena combinación entre precisión y robustez frente a distintos paisajes de optimización.</p>
<p>Por su parte, <code>PSO</code> sobresale en <code>Griewank</code> y <code>Six-Hump Camel</code>. En estos casos logra los mejores valores promedio, lo que indica que su dinámica de exploración y ajuste colectivo se adapta especialmente bien a superficies con múltiples mínimos, pero con una estructura más favorable. Esto muestra que no existe un único método universalmente superior, aunque sí se observa una ventaja general de <code>Evolución diferencial</code> en los problemas más exigentes.</p>
<p>También se nota que la dimensión influye de manera importante en la dificultad. Al pasar de <code>2D</code> a <code>3D</code>, funciones como <code>Rosenbrock</code>, <code>Rastrigin</code>, <code>Schwefel</code> y <code>Griewank</code> presentan un deterioro en el valor promedio, lo que refleja que el aumento de dimensionalidad hace más compleja la búsqueda del óptimo global. Aun así, los métodos mejor posicionados conservan un desempeño competitivo, lo que refuerza la utilidad de estos enfoques heurísticos para problemas no convexos y multimodales.</p>
<p>En síntesis, los resultados sugieren que <code>Evolución diferencial</code> es la alternativa más consistente como método general, mientras que <code>PSO</code> puede ser preferible en funciones específicas donde la estructura del paisaje favorece su estrategia de búsqueda.</p>
</section>
<section id="comparación-gráfica-de-desempeño" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4"><span class="header-section-number">2.3.4</span> Comparación gráfica de desempeño</h3>
<p>Para evitar una presentación excesivamente fragmentada, en la parte heurística conviene resumir los resultados con unas pocas figuras comparativas de alto valor interpretativo. En lugar de repetir una gráfica por cada función y por cada método, es preferible usar figuras consolidadas que permitan identificar rápidamente tendencias generales.</p>
</section>
<section id="comparación-gráfica-de-la-mediana-del-valor-final" class="level3" data-number="2.3.5">
<h3 data-number="2.3.5"><span class="header-section-number">2.3.5</span> Comparación gráfica de la mediana del valor final</h3>
<section id="función-rosenbrock" class="level4" data-number="2.3.5.1">
<h4 data-number="2.3.5.1"><span class="header-section-number">2.3.5.1</span> Función Rosenbrock</h4>
<p><img src="assets/numerica/heuristicos/images/rosenbrock/rosenbrock_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Rosenbrock</code>, <code>Evolución diferencial</code> logra los mejores resultados en <code>2D</code> y <code>3D</code>, con valores muy cercanos al óptimo. Al aumentar la dimensión, <code>PSO</code> y el <code>Algoritmo evolutivo</code> pierden algo de precisión.</p>
</section>
<section id="función-rastrigin" class="level4" data-number="2.3.5.2">
<h4 data-number="2.3.5.2"><span class="header-section-number">2.3.5.2</span> Función Rastrigin</h4>
<p><img src="assets/numerica/heuristicos/images/rastrigin/rastrigin_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Rastrigin</code>, <code>Evolución diferencial</code> y <code>PSO</code> mantienen valores casi nulos en ambas dimensiones. El <code>Algoritmo evolutivo</code> muestra mayores dificultades, sobre todo en <code>3D</code>.</p>
</section>
<section id="función-schwefel" class="level4" data-number="2.3.5.3">
<h4 data-number="2.3.5.3"><span class="header-section-number">2.3.5.3</span> Función Schwefel</h4>
<p><img src="assets/numerica/heuristicos/images/schwefel/schwefel_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Schwefel</code>, <code>Evolución diferencial</code> es el método más estable y preciso en <code>2D</code> y <code>3D</code>. En cambio, <code>PSO</code> empeora con fuerza en <code>3D</code>, mostrando la mayor sensibilidad a la dimensión.</p>
</section>
<section id="función-griewank" class="level4" data-number="2.3.5.4">
<h4 data-number="2.3.5.4"><span class="header-section-number">2.3.5.4</span> Función Griewank</h4>
<p><img src="assets/numerica/heuristicos/images/griewank/griewank_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Griewank</code>, <code>PSO</code> presenta el mejor desempeño general, con valores más cercanos al óptimo en <code>2D</code> y <code>3D</code>. <code>Evolución diferencial</code> también responde bien, mientras que el <code>Algoritmo evolutivo</code> queda más rezagado.</p>
</section>
<section id="función-goldstein-price" class="level4" data-number="2.3.5.5">
<h4 data-number="2.3.5.5"><span class="header-section-number">2.3.5.5</span> Función Goldstein-Price</h4>
<p><img src="assets/numerica/heuristicos/images/goldstein-price/goldstein-price_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Goldstein-Price</code>, los tres métodos tienen resultados parecidos, aunque <code>Evolución diferencial</code> y <code>PSO</code> se mantienen más cerca del valor óptimo. El <code>Algoritmo evolutivo</code> presenta una precisión ligeramente menor.</p>
</section>
<section id="función-six-hump-camel-1" class="level4" data-number="2.3.5.6">
<h4 data-number="2.3.5.6"><span class="header-section-number">2.3.5.6</span> Función Six-Hump Camel</h4>
<p><img src="assets/numerica/heuristicos/images/six-hump%20camel/six-hump%20camel_2d_3d_corridas.png" class="img-fluid" /></p>
<p>En <code>Six-Hump Camel</code>, los tres métodos alcanzan resultados casi idénticos y muy cercanos al óptimo. Esto sugiere que la función puede resolverse con alta estabilidad sin grandes diferencias entre enfoques.</p>
</section>
</section>
<section id="convergencia-por-función" class="level3" data-number="2.3.6">
<h3 data-number="2.3.6"><span class="header-section-number">2.3.6</span> Convergencia por función</h3>
<section id="función-rosenbrock-1" class="level4" data-number="2.3.6.1">
<h4 data-number="2.3.6.1"><span class="header-section-number">2.3.6.1</span> Función Rosenbrock</h4>
<p><img src="assets/numerica/heuristicos/images/rosenbrock/convergencia_rosenbrock_2d_3d.png" class="img-fluid" /></p>
</section>
<section id="función-schwefel-1" class="level4" data-number="2.3.6.2">
<h4 data-number="2.3.6.2"><span class="header-section-number">2.3.6.2</span> Función Schwefel</h4>
<p><img src="assets/numerica/heuristicos/images/schwefel/convergencia_schwefel_2d_3d.png" class="img-fluid" /></p>
</section>
<section id="función-rastrigin-1" class="level4" data-number="2.3.6.3">
<h4 data-number="2.3.6.3"><span class="header-section-number">2.3.6.3</span> Función Rastrigin</h4>
<p><img src="assets/numerica/heuristicos/images/rastrigin/convergencia_rastrigin_2d_3d.png" class="img-fluid" /></p>
</section>
<section id="función-griewank-1" class="level4" data-number="2.3.6.4">
<h4 data-number="2.3.6.4"><span class="header-section-number">2.3.6.4</span> Función Griewank</h4>
<p><img src="assets/numerica/heuristicos/images/griewank/convergencia_griewank_2d_3d.png" class="img-fluid" /></p>
</section>
<section id="función-goldstein-price-1" class="level4" data-number="2.3.6.5">
<h4 data-number="2.3.6.5"><span class="header-section-number">2.3.6.5</span> Función Goldstein-Price</h4>
<p><img src="assets\numerica\heuristicos\images\goldstein-price\convergencia_goldstein-price_2d_3d.png" class="img-fluid" /></p>
</section>
<section id="función-six-hump-camel-2" class="level4" data-number="2.3.6.6">
<h4 data-number="2.3.6.6"><span class="header-section-number">2.3.6.6</span> Función Six-Hump Camel</h4>
<p><img src="assets\numerica\heuristicos\images\six-hump%20camel\convergencia_six-hump%20camel_2d_3d.png" class="img-fluid" /></p>
<p>En general, las curvas muestran que <code>Evolución diferencial</code> es el método más consistente, ya que converge con rapidez y suele terminar más cerca del óptimo en la mayoría de las funciones. <code>PSO</code> también presenta un muy buen desempeño, especialmente en <code>Rastrigin</code>, <code>Griewank</code> y <code>Six-Hump Camel</code>, donde desciende con rapidez y alcanza soluciones competitivas.</p>
<p>Por su parte, el <code>Algoritmo evolutivo</code> tiende a converger de forma más lenta y en varios casos queda más alejado del mejor valor final. En conjunto, los resultados refuerzan que <code>Evolución diferencial</code> y <code>PSO</code> ofrecen el comportamiento de convergencia más favorable dentro del estudio.</p>
</section>
<section id="conclusión-parcial-1" class="level4" data-number="2.3.6.7">
<h4 data-number="2.3.6.7"><span class="header-section-number">2.3.6.7</span> Conclusión Parcial</h4>
<p>Los resultados obtenidos muestran que los métodos heurísticos evaluados son capaces de aproximarse con buena precisión a los óptimos de varias funciones de prueba, aunque su desempeño depende de la complejidad del paisaje y de la dimensión del problema. En general, <code>Evolución diferencial</code> fue el método más consistente, ya que alcanzó valores promedio de <code>0.000000</code> en <code>Rosenbrock 2D</code>, <code>Rastrigin 2D</code> y <code>Goldstein-Price 2D</code>, además de <code>0.000025</code> en <code>Schwefel 2D</code> y <code>0.000038</code> en <code>Schwefel 3D</code>.</p>
<p>Por su parte, <code>PSO</code> también presentó un comportamiento muy competitivo, especialmente en <code>Griewank</code>, donde obtuvo el mejor valor promedio con <code>0.002583</code> en <code>2D</code> y <code>0.009003</code> en <code>3D</code>, y en <code>Six-Hump Camel 2D</code>, donde igualó el mejor resultado con <code>-1.031628</code>. En contraste, el <code>Algoritmo evolutivo</code> mostró un desempeño más variable, con promedios más altos como <code>0.527946</code> en <code>Rosenbrock 3D</code>, <code>0.818432</code> en <code>Rastrigin 3D</code> y <code>4.713732</code> en <code>Schwefel 3D</code>.</p>
<p>Además, se observó que el aumento de dimensionalidad tiende a hacer más difícil la búsqueda del óptimo. Por ejemplo, en <code>Rosenbrock</code> el mejor promedio pasó de <code>0.000000</code> en <code>2D</code> a <code>0.000242</code> en <code>3D</code>, en <code>Rastrigin</code> de <code>0.000000</code> a <code>0.038206</code>, y en <code>Griewank</code> de <code>0.002583</code> a <code>0.009003</code>. Esto confirma que la complejidad del problema influye directamente en la estabilidad y eficacia de los métodos empleados.</p>
<p>En conjunto, el análisis confirma que los métodos heurísticos son una alternativa efectiva para problemas de optimización no lineal y multimodal, pero también evidencia que no existe un único enfoque universalmente superior para todos los casos. Aun así, dentro de este estudio, <code>Evolución diferencial</code> se perfila como la opción más robusta y equilibrada, mientras que <code>PSO</code> destaca en funciones específicas donde alcanza resultados iguales o incluso mejores.</p>
</section>
</section>
</section>
<section id="comparación-final-entre-métodos" class="level2" data-number="2.4">
<h2 data-number="2.4"><span class="header-section-number">2.4</span> Comparación final entre métodos</h2>
<p>Esta página está pensada para comparar los métodos <strong>dentro del mismo caso</strong>, no entre funciones distintas. La comparación correcta es:</p>
<ul>
<li><code>Rosenbrock 2D y 3D</code>: comparación entre descenso por gradiente, algoritmo evolutivo, PSO y evolución diferencial <img src="assets/comparacion/rosenbrock_lineas_por_n.png" class="img-fluid" /> <img src="assets/comparacion/rosenbrock_lineas_desviacion_por_n.png" class="img-fluid" /></li>
</ul>
<p>En la función Rosenbrock, PSO y, especialmente, Evolución diferencial muestran el mejor desempeño, ya que alcanzan valores finales medianos muy cercanos al óptimo tanto en 2D como en 3D y, además, presentan una variabilidad muy baja.</p>
<p>El Algoritmo evolutivo se ubica en un nivel intermedio: mejora con claridad frente a Descenso por gradiente, pero todavía queda algo más alejado del valor óptimo, sobre todo en 3D. En cambio, Descenso por gradiente registra los valores finales más altos y una mayor dispersión, por lo que resulta ser el método menos preciso y menos estable en esta comparación.</p>
<ul>
<li><code>Rastrigin 2D y 3D</code>: gradiente vs EA vs PSO vs DE <img src="assets/comparacion/rastrigin_lineas_por_n.png" class="img-fluid" /> <img src="assets/comparacion/rastrigin_lineas_desviacion_por_n.png" class="img-fluid" /></li>
</ul>
<p>Para la función Rastrigin, la diferencia entre métodos es aún más evidente. Evolución diferencial y PSO vuelven a destacar como las alternativas más efectivas, al mantener valores finales muy próximos al óptimo y desviaciones reducidas, incluso cuando aumenta la dimensión del problema.</p>
<p>El Algoritmo evolutivo ofrece un comportamiento aceptable, pero sigue mostrando una brecha frente a los mejores métodos. Por su parte, Descenso por gradiente presenta los peores resultados, con valores finales claramente más altos y una variabilidad mayor, lo que indica menor capacidad para converger de forma precisa en esta función.</p>
<ul>
<li><code>Schwefel 2D y 3D</code>: gradiente vs EA vs PSO vs DE <img src="assets/comparacion/schwefel_lineas_por_n.png" class="img-fluid" /> <img src="assets/comparacion/schwefel_lineas_desviacion_por_n.png" class="img-fluid" /></li>
</ul>
<p>En la función Schwefel, <code>Evolución diferencial</code> es el método más sólido en ambas dimensiones, ya que mantiene valores finales medianos prácticamente sobre el óptimo y, además, exhibe la menor desviación entre todos los enfoques. El <code>Algoritmo evolutivo</code> también presenta un muy buen comportamiento, con resultados cercanos al óptimo y una variabilidad bastante baja, aunque sin alcanzar la consistencia de <code>DE</code>. En contraste, <code>PSO</code> y, sobre todo, <code>Descenso por gradiente</code> muestran un desempeño más débil: <code>PSO</code> se deteriora con claridad en 3D, mientras que <code>Descenso por gradiente</code> conserva los valores finales más altos y la mayor dispersión, por lo que resulta el método menos preciso y menos estable en esta comparación.</p>
<ul>
<li><code>Griewank 2D y 3D</code>: gradiente vs EA vs PSO vs DE <img src="assets/comparacion/griewank_lineas_por_n.png" class="img-fluid" /> <img src="assets/comparacion/griewank_lineas_desviacion_por_n.png" class="img-fluid" /></li>
</ul>
<p>En la función Griewank se observa un comportamiento menos uniforme entre métodos que en los casos anteriores. En 2D, <code>Evolución diferencial</code> logra el mejor resultado, ya que se mantiene prácticamente sobre el óptimo y con la menor desviación, mientras que <code>PSO</code> también presenta un desempeño bastante sólido.</p>
<p>En 3D, el método que mejor se comporta es <code>PSO</code>, porque alcanza los valores medianos más bajos y conserva una variabilidad reducida; <code>Evolución diferencial</code> se mantiene competitivo, aunque ya no domina con la misma claridad que en 2D.</p>
<p>Por otro lado, el <code>Algoritmo evolutivo</code> es el más débil en ambas dimensiones, al registrar los valores finales más altos y la mayor dispersión, mientras que <code>Descenso por gradiente</code> queda en una posición intermedia.</p>
<ul>
<li><code>Goldstein-Price 2D</code>: gradiente vs EA vs PSO vs DE
<p style="display: flex; gap: 12px;">
<img src="assets/comparacion/goldstein_price_lineas_por_n.png" width="49%" /> <img src="assets/comparacion/goldstein_price_lineas_desviacion_por_n.png" width="49%" />
</p></li>
</ul>
<p>En la función <code>Goldstein-Price 2D</code>, <code>PSO</code> y <code>Evolución diferencial</code> muestran el mejor comportamiento, ya que alcanzan valores finales medianos prácticamente coincidentes con el óptimo y, además, presentan una variabilidad extremadamente baja. El <code>Algoritmo evolutivo</code> también logra aproximarse bien al valor óptimo, aunque con una dispersión mayor que estos dos métodos. En contraste, <code>Descenso por gradiente</code> es claramente el más débil, porque se mantiene muy alejado del óptimo y exhibe la mayor desviación, lo que refleja menor precisión y menor estabilidad.</p>
<ul>
<li><code>Six-Hump Camel 2D</code>: gradiente vs EA vs PSO vs DE
<p style="display: flex; gap: 12px;">
<img src="assets/comparacion/six_hump_camel_lineas_por_n.png" width="49%" /> <img src="assets\comparacion\six_hump_camel_lineas_desviacion_por_n.png" width="49%" />
</p></li>
</ul>
<p>En la función <code>Six-Hump Camel 2D</code>, <code>PSO</code> y <code>Evolución diferencial</code> son los métodos más precisos, ya que se mantienen prácticamente sobre el valor óptimo y presentan una dispersión extremadamente baja. El <code>Algoritmo evolutivo</code> también logra resultados cercanos, aunque sus valores medianos quedan ligeramente por encima del óptimo y muestran una variabilidad mayor.</p>
<p>Por su parte, <code>Descenso por gradiente</code> es el enfoque menos estable, al registrar con diferencia la desviación más alta entre todos los métodos comparados.</p>
<section id="tabla-comparativa-global" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1"><span class="header-section-number">2.4.1</span> Tabla comparativa global</h3>
<table class="caption-top">
<colgroup>
<col style="width: 33%" />
<col style="width: 33%" />
<col style="width: 33%" />
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th>Mejor método en valor final o distancia al óptimo</th>
<th>Mejor método en evaluaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Goldstein-Price 2D</td>
<td>Evolución diferencial</td>
<td>Evolución diferencial</td>
</tr>
<tr class="even">
<td>Griewank 2D</td>
<td>PSO</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="odd">
<td>Griewank 3D</td>
<td>PSO</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="even">
<td>Rastrigin 2D</td>
<td>Evolución diferencial</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="odd">
<td>Rastrigin 3D</td>
<td>Evolución diferencial</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="even">
<td>Rosenbrock 2D</td>
<td>Evolución diferencial</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="odd">
<td>Rosenbrock 3D</td>
<td>Evolución diferencial</td>
<td>Descenso por gradiente</td>
</tr>
<tr class="even">
<td>Schwefel 2D</td>
<td>Evolución diferencial</td>
<td>Evolución diferencial</td>
</tr>
<tr class="odd">
<td>Schwefel 3D</td>
<td>Evolución diferencial</td>
<td>Evolución diferencial</td>
</tr>
<tr class="even">
<td>Six-Hump Camel 2D</td>
<td>PSO</td>
<td>Descenso por gradiente</td>
</tr>
</tbody>
</table>
</section>
<section id="conteo-global-de-victorias" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2"><span class="header-section-number">2.4.2</span> Conteo global de victorias</h3>
<p>Aquí se presenta un cierre simple contando cuántas veces ganó cada método.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Método</th>
<th style="text-align: right;">Veces que ganó en calidad</th>
<th style="text-align: right;">Veces que ganó en evaluaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gradiente</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>EA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>PSO</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>DE</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusiones" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3"><span class="header-section-number">2.4.3</span> Conclusiones</h3>
<section id="conclusión-1-mejor-calidad-de-solución-en-los-métodos-heurísticos" class="level4" data-number="2.4.3.1">
<h4 data-number="2.4.3.1"><span class="header-section-number">2.4.3.1</span> <strong>Conclusión 1: Mejor calidad de solución en los métodos heurísticos</strong></h4>
<p>En términos de calidad de solución, los métodos heurísticos dominaron la comparación: ganaron en los <code>10 de 10</code> casos analizados. Dentro de ese grupo, <code>Evolución diferencial</code> obtuvo el mejor resultado en <code>7</code> casos y <code>PSO</code> en <code>3</code>, mientras que <code>Algoritmo evolutivo</code> y <code>Descenso por gradiente</code> no lideraron ningún caso en esta métrica.</p>
</section>
<section id="conclusión-2-mayor-eficiencia-computacional-del-descenso-por-gradiente" class="level4" data-number="2.4.3.2">
<h4 data-number="2.4.3.2"><span class="header-section-number">2.4.3.2</span> <strong>Conclusión 2: Mayor eficiencia computacional del descenso por gradiente</strong></h4>
<p>En costo computacional, medido por el número de evaluaciones de la función objetivo, <code>Descenso por gradiente</code> fue el método más eficiente en <code>7 de 10</code> casos. Los <code>3</code> casos restantes fueron ganados por <code>Evolución diferencial</code>, lo que muestra que gradiente suele ser más barato, aunque no necesariamente el más preciso.</p>
</section>
<section id="conclusión-3-aporte-comparado-entre-descenso-por-gradiente-y-métodos-heurísticos" class="level4" data-number="2.4.3.3">
<h4 data-number="2.4.3.3"><span class="header-section-number">2.4.3.3</span> <strong>Conclusión 3: Aporte comparado entre descenso por gradiente y métodos heurísticos</strong></h4>
<p>Los resultados muestran un patrón claro: los métodos heurísticos aportaron mejor precisión global, mientras que <code>Descenso por gradiente</code> aportó mayor rapidez en la mayoría de los casos. Además, <code>Evolución diferencial</code> fue el único método que logró combinar ambas ventajas en algunos problemas, siendo el mejor tanto en calidad como en evaluaciones en <code>3</code> casos: <code>Goldstein-Price 2D</code>, <code>Schwefel 2D</code> y <code>Schwefel 3D</code>.</p>
</section>
</section>
<section id="animación-representativa-del-método-ganador" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4"><span class="header-section-number">2.4.4</span> Animación representativa del método ganador</h3>
<p>Como cierre visual de la comparación numérica, se incluye una animación de <code>evolución diferencial</code> sobre la función <code>Rastrigin 2D</code>. Este caso se eligió porque <code>DE</code> fue el método con mejor desempeño global en la comparación final y porque <code>Rastrigin</code> presenta una superficie altamente multimodal, con muchos mínimos locales, lo que permite visualizar con claridad la capacidad de exploración del algoritmo.</p>
<p>La animación resume de manera intuitiva por qué los métodos heurísticos, y en particular la evolución diferencial, pueden ofrecer ventajas frente a un método local cuando el paisaje de optimización es complejo, ya que fueron diseñados para la optimización global en espacios continuos y favorecen una exploración más robusta del espacio de búsqueda <span class="citation" data-cites="storn1997">(<a href="#ref-storn1997" role="doc-biblioref">Storn and Price 1997</a>)</span>.</p>
<p><img src="assets/histogramas/animacion_de_rastrigin_2d_semilla_1612.gif" class="img-fluid" /></p>
</section>
<section id="fuente-de-datos" class="level3" data-number="2.4.5">
<h3 data-number="2.4.5"><span class="header-section-number">2.4.5</span> Fuente de datos</h3>
<p>Esta comparación debe salir de:</p>
<ul>
<li><a href="notebooks/numerica/gradiente/analisis_resultados.ipynb">analisis_resultados.ipynb</a></li>
<li><a href="notebooks/numerica/heuristicos/analisis_resultados.ipynb">analisis_resultados.ipynb</a></li>
<li><a href="notebooks/numerica/12_comparacion_final_metodos.ipynb">12_comparacion_final_metodos.ipynb</a></li>
</ul>
</section>
</section>
</section>
<section id="parte-2-optimización-combinatoria-tsp---96-departamentos-de-francia" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Parte 2: Optimización Combinatoria (TSP - 96 Departamentos de Francia)</h1>
<section id="descripción-del-problema" class="level2" data-number="3.1">
<h2 data-number="3.1"><span class="header-section-number">3.1</span> 3.1 Descripción del problema</h2>
<p>En la segunda parte del trabajo se aborda una variante del <strong>Problema del Viajante (TSP)</strong> aplicada al recorrido de las <strong>96 capitales departamentales de Francia metropolitana</strong>. El objetivo consiste en encontrar un orden de visita para todas las ciudades tal que se minimice el costo total del recorrido, cumpliendo la condición clásica del TSP: cada ciudad debe visitarse exactamente una vez y, al finalizar, se debe completar el circuito regresando al punto de partida o cerrando la gira definida para la evaluación. Debido a que el número de rutas posibles crece de forma factorial con respecto al número de ciudades, se trata de un problema combinatorio de muy alta complejidad, para el cual resulta poco práctico aplicar métodos exactos en tiempos razonables <span class="citation" data-cites="applegate2006">(<a href="#ref-applegate2006" role="doc-biblioref">Applegate et al. 2006</a>)</span>.</p>
<p>En este contexto, cada solución candidata puede representarse como una permutación de las 96 ciudades, donde el orden de los elementos define la ruta seguida por el vendedor. Sin embargo, la evaluación de esa ruta no se realiza directamente sobre el grafo parcial original, sino sobre una matriz completa de costos mínimos entre todas las parejas de ciudades. De esta manera, el problema no se limita a encontrar la ruta más corta en kilómetros, sino la ruta de <strong>menor costo total</strong>, incorporando factores operativos más cercanos a una situación real de desplazamiento y dejando la instancia lista para ser tratada como un TSP clásico.</p>
<p>La función objetivo utilizada en la implementación combina directamente tres componentes por tramo: <strong>peajes</strong>, <strong>gasolina</strong> y <strong>costo del tiempo del vendedor</strong>. En particular, el componente de combustible no se estima como distancia por costo por kilómetro, sino que se toma directamente de la columna <code>gasolina(euros)</code> recuperada del dataset. A esto se suma el costo temporal del vendedor, calculado a partir del tiempo de viaje y una tarifa fija de <strong>12.02 EUR/h</strong>. En forma compacta, la expresión empleada es:</p>
<p><span class="math display">\[
\text{Costo total} = \text{peajes(euros)} + \text{gasolina(euros)} + \left(\frac{\text{tiempo(min)}}{60}\right)\times 12.02
\]</span></p>
<p>Bajo esta formulación, el costo total de un tour se obtiene acumulando ese valor sobre los tramos recorridos en la ruta. Esto hace que el problema sea especialmente adecuado para el uso de metaheurísticas, ya que el reto consiste en explorar un espacio enorme de posibles recorridos y encontrar una secuencia que balancee de manera eficiente tiempo y costo monetario en una red vial real.</p>
</section>
<section id="construcción-y-preprocesamiento-de-datos" class="level2" data-number="3.2">
<h2 data-number="3.2"><span class="header-section-number">3.2</span> 3.2 Construcción y preprocesamiento de datos</h2>
<p>La construcción del conjunto de datos para esta parte del trabajo se realizó en varias etapas. Primero, se extrajeron las coordenadas geográficas de las ciudades desde el sitio web <a href="https://geokeo.com/database/town/fr/23/">GeoKeo</a>, tomando como referencia las capitales departamentales de Francia. A partir de estas coordenadas se generó una primera estructura de conexiones entre ciudades cercanas, utilizada como base para construir un grafo inicial de rutas, el cual fue exportado a un archivo CSV para facilitar su revisión posterior.</p>
<p>Posteriormente, este grafo fue ajustado y validado manualmente con apoyo de visualizaciones sobre mapa, con el fin de identificar conexiones plausibles dentro de la red y corregir aquellas que no representaban trayectos razonables. Esta etapa fue importante porque la cercanía geográfica por sí sola no garantiza que dos ciudades estén conectadas por una ruta real o conveniente dentro de la red vial.</p>
<p>Una vez consolidada esta red base, se realizó el proceso de <code>web scraping</code> sobre el sitio <a href="https://www.vinci-autoroutes.com/fr/mon-trajet/">VINCI Autoroutes</a>, utilizando las rutas previamente definidas para consultar y completar información real de los trayectos. En particular, para cada conexión se obtuvo la distancia recorrida, el tiempo estimado de viaje y el valor de los peajes. Para mantener consistencia en la recolección de la información, en VINCI Autoroutes se utilizó la categoría <strong>Clase 1 - Vehículos ligeros</strong>, correspondiente a automóviles particulares y vehículos de uso ligero <span class="citation" data-cites="vinci2026">(<a href="#ref-vinci2026" role="doc-biblioref">VINCI Autoroutes 2026</a>)</span>. Estos datos sirvieron como base para estructurar el conjunto final utilizado en la optimización combinatoria.</p>
<p>Como paso previo a la optimización, se calculó el costo mínimo de viaje entre cada par de ciudades a partir de la red de conexiones disponibles. Para ello se aplicó el algoritmo de Dijkstra, un método clásico para encontrar caminos de costo mínimo en grafos <span class="citation" data-cites="dijkstra1959">(<a href="#ref-dijkstra1959" role="doc-biblioref">Dijkstra 1959</a>)</span>. De esta forma se construyó una matriz completa de costos <code>96 x 96</code>, que fue la utilizada posteriormente por ACO y GA. Sobre esa matriz se verificó que la estructura fuera cuadrada, que la diagonal quedara en cero y que no existieran valores infinitos fuera de la diagonal, asegurando así una representación consistente del problema.</p>
<p><a href="notebooks/combinatoria/00_construccion_grafo_inicial.ipynb" class="notebook-card-link"> <span class="notebook-card-icon"> <svg width="24" height="24" viewBox="0 0 64 64" fill="none" aria-hidden="true"> <ellipse cx="32" cy="32" rx="17" ry="10.5" stroke="#f37726" stroke-width="4.5"></ellipse> <circle cx="50.5" cy="21" r="3.2" fill="#9e9e9e"></circle> <circle cx="13.5" cy="43" r="3.2" fill="#9e9e9e"></circle> </svg> </span> <span class="notebook-card-title">Cuaderno de construcción inicial del grafo</span> </a></p>
</section>
<section id="algoritmos-utilizados" class="level2" data-number="3.3">
<h2 data-number="3.3"><span class="header-section-number">3.3</span> 3.3 Algoritmos utilizados</h2>
<p>Para resolver este problema se emplearon dos metaheurísticas clásicas para optimización combinatoria: <strong>Colonia de Hormigas (ACO)</strong> y <strong>Algoritmos Genéticos (GA)</strong>. La elección de estos métodos responde a que ambos están diseñados para explorar espacios de búsqueda discretos muy grandes y han mostrado buen desempeño en variantes del TSP. Además, permiten balancear de manera flexible los procesos de exploración y explotación, lo cual es importante cuando se busca escapar de soluciones pobres sin perder la capacidad de refinar rutas prometedoras <span class="citation" data-cites="talbi2009">(<a href="#ref-talbi2009" role="doc-biblioref">Talbi 2009</a>)</span>.</p>
<section id="colonia-de-hormigas-aco" class="level4" data-number="3.3.0.1">
<h4 data-number="3.3.0.1"><span class="header-section-number">3.3.0.1</span> Colonia de Hormigas (ACO)</h4>
<p>El algoritmo de colonia de hormigas construye soluciones de manera progresiva, simulando el comportamiento colectivo de hormigas que depositan feromonas sobre los caminos recorridos. En cada iteración, varias hormigas generan rutas completas entre las ciudades, eligiendo el siguiente nodo con base en una combinación entre la <strong>feromona acumulada</strong> y una <strong>heurística local</strong> asociada al inverso del costo entre ciudades. Con el paso de las iteraciones, las rutas de menor costo reciben mayor refuerzo y tienden a guiar la búsqueda hacia regiones más prometedoras del espacio de soluciones.</p>
<p>En la implementación utilizada se fijaron los siguientes parámetros:</p>
<ul>
<li>número de hormigas: <code>40</code></li>
<li>número de iteraciones: <code>250</code></li>
<li>importancia de la feromona (<code>alpha</code>): <code>1.0</code></li>
<li>importancia de la heurística (<code>beta</code>): <code>3.0</code></li>
<li>tasa de evaporación: <code>0.35</code></li>
<li>factor de intensificación: <code>2.0</code></li>
<li>peso elitista para reforzar la mejor ruta global: <code>2.0</code></li>
<li>semilla aleatoria: <code>42</code></li>
</ul>
</section>
<section id="experimentación-con-distintas-configuraciones" class="level4" data-number="3.3.0.2">
<h4 data-number="3.3.0.2"><span class="header-section-number">3.3.0.2</span> Experimentación con distintas configuraciones</h4>
<ul>
<li>Experimento cambiando <code>número de hormigas</code>:</li>
</ul>
<p><img src="assets\combinatoria\aco\aco_ants.png" class="img-fluid" /></p>
<p>La gráfica muestra que todas las configuraciones mejoran con rapidez en las primeras iteraciones y luego se estabilizan, así que 250 iteraciones parecen más de las necesarias para este experimento. La mejor configuración fue la de 80 hormigas, ya que alcanzó el menor costo final (aprox. 4100), mientras que 20 hormigas obtuvo el peor resultado. En general, aumentar el número de hormigas parece mejorar la exploración y permitir mejores soluciones, aunque la mejora no es totalmente uniforme entre todas las configuraciones. De todos modos, como aquí se usa una sola semilla, sería recomendable repetir el experimento con varias corridas y también comparar contra tiempo de ejecución, porque más hormigas implican mayor costo computacional.</p>
<ul>
<li>Experimento cambiando <code>beta</code>:</li>
</ul>
<p><img src="assets\combinatoria\aco\aco_beta.png" class="img-fluid" /></p>
<p>Aquí se ve más claro el efecto de <code>beta</code>: cuando <strong>beta es bajo (<code>3.0</code>)</strong>, el algoritmo converge más lento y además termina con el <strong>peor costo final</strong>. En cambio, con valores más altos, la convergencia mejora bastante y se alcanzan soluciones de mejor calidad.</p>
<p>Las mejores configuraciones parecen ser <strong><code>beta = 5.0</code> y <code>beta = 7.0</code></strong>, que llegan a los <strong>costos más bajos</strong> (cerca de 4100), mientras que <strong><code>beta = 6.0</code> y <code>beta = 4.0</code></strong> quedan en un punto intermedio. En general, esto sugiere que <strong>dar más peso a la heurística ayuda</strong>, aunque el efecto no es totalmente lineal, porque no todos los valores altos de <code>beta</code> rinden igual.</p>
<p>Estos valores permiten dar mayor peso a la información heurística del costo entre ciudades, sin eliminar la influencia del aprendizaje colectivo por feromonas. La evaporación evita que la búsqueda se estanque demasiado pronto en rutas subóptimas, mientras que el refuerzo elitista ayuda a conservar y explotar la mejor solución global encontrada hasta cada iteración.</p>
<ul>
<li>Experimento cambiando <code>evaporation rate</code>:</li>
</ul>
<p><img src="assets\combinatoria\aco\aco_evaporation_rate.png" class="img-fluid" /></p>
<p>Aquí se ve que la <strong>tasa de evaporación sí cambia bastante el comportamiento</strong> del ACO. Con <strong><code>0.25</code></strong> se obtiene el <strong>mejor costo final</strong> (aprox. <strong>4060</strong>), aunque no es la curva que baja más rápido al inicio. En cambio, con <strong><code>0.55</code></strong> la mejora inicial es muy rápida, pero se estanca pronto y termina con el <strong>peor resultado final</strong>.</p>
<p>En general, esto sugiere que una evaporación <strong>intermedia</strong> funciona mejor: si es <strong>muy baja</strong> (<code>0.15</code>), el algoritmo tarda más en adaptarse; si es <strong>muy alta</strong> (<code>0.55</code>), pierde demasiado rápido la información acumulada. Por eso, en este experimento, <strong><code>0.25</code> parece el mejor equilibrio entre exploración y explotación</strong>.</p>
</section>
<section id="configuración-final-de-parámetros-para-el-modelo-de-colonia-de-hormigas" class="level4" data-number="3.3.0.3">
<h4 data-number="3.3.0.3"><span class="header-section-number">3.3.0.3</span> Configuración final de parámetros para el modelo de Colonia de Hormigas</h4>
<p>De acuerdo con los experimentos realizados, se estableció la siguiente configuración para el algoritmo de colonia de hormigas (ACO), buscando un equilibrio entre la exploración del espacio de soluciones y la explotación de las mejores rutas encontradas:</p>
<ul>
<li>número de hormigas: <code>150</code></li>
<li>número de iteraciones: <code>100</code></li>
<li>importancia de la feromona (<code>alpha</code>): <code>1.0</code></li>
<li>importancia de la heurística (<code>beta</code>): <code>5.0</code></li>
<li>tasa de evaporación: <code>0.25</code></li>
<li>factor de intensificación: <code>2.0</code></li>
<li>peso elitista para reforzar la mejor ruta global: <code>2.0</code></li>
<li>semilla aleatoria: <code>no especificada</code></li>
</ul>
</section>
<section id="algoritmos-genéticos-ga" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1"><span class="header-section-number">3.3.1</span> Algoritmos Genéticos (GA)</h3>
<p>El algoritmo genético aborda el problema manteniendo una <strong>población de rutas candidatas</strong> que evoluciona a lo largo de varias generaciones. Cada individuo representa un recorrido completo por las ciudades, y su aptitud se evalúa con el costo total de la ruta. A partir de esta evaluación, se seleccionan las mejores soluciones para producir descendencia mediante operadores de cruce y mutación. De este modo, el método combina información de rutas de buena calidad y genera nuevas alternativas que pueden mejorar progresivamente el resultado obtenido.</p>
<p>En este trabajo, el GA se implementó con una estrategia de <strong>selección por torneo</strong>, <strong>cruce ordenado</strong> y <strong>mutación por intercambio</strong> de posiciones dentro de la ruta. Además, se permitió inyectar como semilla inicial la mejor ruta producida por ACO, con el fin de aprovechar una buena solución de partida y refinarla en una fase evolutiva posterior.</p>
<p>Los parámetros iniciales usados fueron:</p>
<ul>
<li>tamaño de población: <code>180</code></li>
<li>número de generaciones: <code>350</code></li>
<li>tasa de mutación: <code>0.12</code></li>
<li>tasa de cruce: <code>0.9</code></li>
<li>número de individuos elitistas preservados por generación: <code>12</code></li>
<li>tamaño del torneo de selección: <code>5</code></li>
<li>uso de semilla inicial proveniente de ACO: <code>True</code></li>
<li>semilla aleatoria: <code>42</code></li>
</ul>
<p>La justificación de esta configuración es que una población relativamente amplia favorece la diversidad de soluciones, mientras que una tasa de cruce alta promueve la recombinación de rutas prometedoras. La mutación moderada introduce variación sin destruir excesivamente las estructuras útiles encontradas, y el elitismo garantiza que las mejores soluciones no se pierdan entre generaciones.</p>
<section id="experimentación-con-distintas-configuraciones-1" class="level4" data-number="3.3.1.1">
<h4 data-number="3.3.1.1"><span class="header-section-number">3.3.1.1</span> Experimentación con distintas configuraciones</h4>
<ul>
<li>Experimento cambiando <code>tasa de mutación</code>:</li>
</ul>
<p><img src="assets\combinatoria\ga\ga_mutation_rate.png" class="img-fluid" /></p>
<p>Aquí se ve que <strong>todas las tasas de mutación terminan llegando prácticamente al mismo costo final</strong> (cerca de <strong>3975</strong>), así que en este experimento la diferencia no está tanto en la calidad final sino en la <strong>velocidad de convergencia</strong>. La más lenta es <strong><code>mutation_rate = 0.12</code></strong>, mientras que <strong><code>0.24</code> y <code>0.28</code></strong> encuentran mejoras antes.</p>
<p>En general, esto sugiere que una <strong>mutación moderadamente alta ayuda a acelerar la búsqueda</strong> sin perjudicar el resultado final. Si tuvieras que escoger una opción balanceada, <strong><code>mutation_rate = 0.24</code></strong> se ve como una muy buena candidata, porque converge rápido sin irse al valor más extremo.</p>
<ul>
<li>Experimento cambiando <code>tamaño de población</code>:</li>
</ul>
<p><img src="assets\combinatoria\ga\ga_population_rate.png" class="img-fluid" /></p>
<p>Aquí se ve que tamaños de población más grandes convergen más rápido: 340 y 300 encuentran mejoras antes, mientras que 180 es claramente la más lenta. Sin embargo, todas terminan llegando prácticamente al mismo costo final (cerca de 3975), así que la diferencia principal está en la rapidez, no en la calidad final.</p>
<p>Eso sugiere que aumentar population_size ayuda a acelerar la búsqueda, pero con rendimientos decrecientes. Como además una población más grande cuesta más por generación, no necesariamente conviene irse al valor máximo. Si buscas una opción balanceada, population_size = 260 o 300 se ven como candidatas razonables.</p>
<ul>
<li>Experimento cambiando <code>uso de semilla inicial proveniente de ACO</code>:</li>
</ul>
<p><img src="assets\combinatoria\ga\ga_aco_seed.png" class="img-fluid" /></p>
<p>Aquí la diferencia es muy marcada: usar ACO seed hace que el GA arranque desde un costo mucho mejor, cerca de 4000, mientras que sin ACO seed empieza alrededor de 19400 y, aunque mejora de forma sostenida, después de 200 generaciones todavía queda muy por encima.</p>
<p>Esto sugiere que inyectar la solución de ACO es altamente beneficioso, porque acelera muchísimo la convergencia y además lleva al algoritmo a una región de soluciones mucho mejores desde el inicio. De hecho, con ACO seed casi no hay mejoras adicionales, lo que indica que ACO ya entrega una solución inicial muy fuerte y el GA solo la refina ligeramente.</p>
</section>
</section>
</section>
<section id="configuración-final-de-parámetros-para-el-algoritmo-genético" class="level2" data-number="3.4">
<h2 data-number="3.4"><span class="header-section-number">3.4</span> Configuración final de parámetros para el algoritmo genético</h2>
<p>De acuerdo con los experimentos realizados, se estableció la siguiente configuración para el algoritmo genético (GA), buscando un equilibrio entre diversidad poblacional, intensidad de búsqueda y preservación de las mejores soluciones encontradas:</p>
<ul>
<li>tamaño de población: <code>300</code></li>
<li>número de generaciones: <code>200</code></li>
<li>tasa de mutación: <code>0.24</code></li>
<li>tasa de cruce: <code>0.9</code></li>
<li>número de individuos elitistas preservados por generación: <code>12</code></li>
<li>tamaño del torneo de selección: <code>5</code></li>
<li>uso de semilla inicial proveniente de ACO: <code>True</code></li>
<li>semilla aleatoria: <code>42</code></li>
</ul>
</section>
<section id="resultados" class="level2" data-number="3.5">
<h2 data-number="3.5"><span class="header-section-number">3.5</span> 3.4 Resultados</h2>
<p>Los experimentos realizados sobre la instancia de las 96 capitales departamentales muestran que ambos métodos fueron capaces de producir recorridos válidos y de costo competitivo. Sin embargo, el mejor resultado final fue alcanzado por el <strong>algoritmo genético (GA)</strong>, que logró refinar la solución inicial y obtener un costo total inferior al conseguido por la colonia de hormigas.</p>
<p>La comparación final entre métodos puede resumirse en la siguiente tabla:</p>
<table class="caption-top">
<colgroup>
<col style="width: 15%" />
<col style="width: 21%" />
<col style="width: 21%" />
<col style="width: 21%" />
<col style="width: 21%" />
</colgroup>
<thead>
<tr class="header">
<th>Método</th>
<th style="text-align: right;">Mejor costo del tour (EUR)</th>
<th style="text-align: right;">Diferencia frente al mejor (EUR)</th>
<th style="text-align: right;">Iteraciones / generaciones</th>
<th style="text-align: right;">Tamaño de búsqueda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GA</td>
<td style="text-align: right;">3975.266333</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">350</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="even">
<td>ACO</td>
<td style="text-align: right;">4022.039333</td>
<td style="text-align: right;">46.773000</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">150</td>
</tr>
</tbody>
</table>
<p>El <strong>mejor costo encontrado</strong> fue de <strong>3975.266333 euros</strong>, calculado con la función de costo definida a partir de peajes, combustible y tiempo del vendedor. Este resultado se obtuvo usando como vehículo de referencia un <strong>Renault Clio</strong>, con combustible tipo gasolina, y una tarifa del vendedor de <strong>12.02 euros por hora</strong>, de acuerdo con la formulación del modelo. Además, aunque el tour TSP recorre las <strong>96 capitales</strong>, su expansión sobre el grafo real produce un recorrido de <strong>100 saltos reales</strong>, lo que permite interpretar la solución final de manera más fiel a la red de conexiones utilizada.</p>
<p>En cuanto a la comparación entre métodos, ACO alcanzó un mejor costo de <strong>4022.039333 euros</strong>, mientras que GA obtuvo <strong>3975.266333 euros</strong>. En otras palabras, <strong>GA mejoró a ACO en 46.773000 euros, equivalente a una mejora relativa de 1.1629 %</strong>. Esta diferencia es menor que en versiones preliminares de los experimentos, lo que indica que ambos métodos terminaron convergiendo a soluciones de alta calidad y muy cercanas entre sí.</p>
<p>Desde el punto de vista de la convergencia, esta dinámica resulta especialmente interesante. ACO encuentra con rapidez una solución base competitiva para una instancia grande del TSP, mientras que GA, apoyado en una población más amplia y en la inyección de la mejor solución previa de ACO, consigue seguir refinando la ruta hasta obtener la mejor solución final. En este sentido, los resultados no solo muestran competencia entre ambos enfoques, sino también una <strong>complementariedad efectiva</strong> dentro del flujo de optimización.</p>
<p>La <strong>mejor ruta encontrada</strong> puede resumirse por tramos geográficos de la siguiente forma:</p>
<ul>
<li>corredor este y noreste: <code>Bourg-en-Bresse -&gt; Lons-le-Saunier -&gt; Besançon -&gt; Vesoul -&gt; Belfort -&gt; Colmar -&gt; Strasbourg -&gt; Metz -&gt; Nancy -&gt; Épinal -&gt; Chaumont -&gt; Dijon -&gt; Auxerre -&gt; Troyes -&gt; Bar-le-Duc -&gt; Châlons-en-Champagne -&gt; Charleville-Mézières -&gt; Laon</code></li>
<li>norte y eje parisino: <code>Lille -&gt; Arras -&gt; Amiens -&gt; Beauvais -&gt; Cergy -&gt; Nanterre -&gt; Bobigny -&gt; Créteil -&gt; Paris -&gt; Versailles -&gt; Évry-Courcouronnes -&gt; Melun</code></li>
<li>centro-oeste y fachada atlántica: <code>Orléans -&gt; Blois -&gt; Tours -&gt; Poitiers -&gt; Niort -&gt; La Rochelle -&gt; La Roche-sur-Yon -&gt; Nantes -&gt; Vannes -&gt; Quimper -&gt; Saint-Brieuc -&gt; Rennes -&gt; Laval -&gt; Angers -&gt; Le Mans -&gt; Alençon -&gt; Caen -&gt; Saint-Lô -&gt; Rouen -&gt; Évreux -&gt; Chartres -&gt; Bourges -&gt; Châteauroux -&gt; Guéret -&gt; Limoges -&gt; Tulle -&gt; Aurillac</code></li>
<li>suroccidente y arco mediterráneo: <code>Rodez -&gt; Albi -&gt; Montauban -&gt; Cahors -&gt; Agen -&gt; Périgueux -&gt; Angoulême -&gt; Bordeaux -&gt; Mont-de-Marsan -&gt; Pau -&gt; Tarbes -&gt; Auch -&gt; Toulouse -&gt; Foix -&gt; Carcassonne -&gt; Perpignan -&gt; Montpellier -&gt; Nîmes -&gt; Avignon -&gt; Marseille -&gt; Toulon -&gt; Bastia -&gt; Ajaccio -&gt; Nice -&gt; Digne-les-Bains -&gt; Gap</code></li>
<li>retorno alpino y centro-este: <code>Grenoble -&gt; Valence -&gt; Privas -&gt; Mende -&gt; Le Puy-en-Velay -&gt; Saint-Étienne -&gt; Clermont-Ferrand -&gt; Moulins -&gt; Nevers -&gt; Mâcon -&gt; Lyon -&gt; Chambéry -&gt; Annecy -&gt; Bourg-en-Bresse</code></li>
</ul>
<p>En términos cualitativos, los resultados muestran una dinámica complementaria entre ambos enfoques. ACO aporta una exploración guiada por información local y memoria colectiva, lo que permite encontrar rápidamente rutas razonables en un espacio de búsqueda muy grande. Por su parte, GA aprovecha esa base inicial y la mejora mediante operadores evolutivos, conservando buenas estructuras parciales y corrigiendo tramos menos eficientes del recorrido. Por esta razón, dentro de los experimentos realizados, <strong>GA puede considerarse el método con mejor desempeño final</strong> para esta instancia del problema, aunque la brecha observada frente a ACO sugiere que ambos métodos fueron altamente competitivos.</p>
</section>
<section id="visualización" class="level2" data-number="3.6">
<h2 data-number="3.6"><span class="header-section-number">3.6</span> 3.5 Visualización</h2>
<p>La visualización final se realiza sobre el mapa de <strong>Francia</strong>, mostrando el recorrido ganador obtenido por el algoritmo genético. El GIF permite observar la progresión espacial del tour, mientras que la curva de convergencia muestra cómo el costo va disminuyendo a medida que avanzan las generaciones del método ganador.</p>
<section id="comparación-visual-de-costos" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1"><span class="header-section-number">3.6.1</span> Comparación visual de costos</h3>
<iframe src="assets\combinatoria\visualizacion_mejor_solucion_mapa.html" width="100%" height="760" style="border:0; border-radius:18px;">
</iframe>
</section>
<section id="gif-del-mejor-recorrido-en-francia" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2"><span class="header-section-number">3.6.2</span> GIF del mejor recorrido en Francia</h3>
<p><img src="assets/combinatoria/mejor_solucion_combinatoria.gif" alt="GIF del mejor recorrido sobre Francia" style="max-width: 100%; height: auto;"></p>
</section>
<section id="curva-de-convergencia-del-método-ganador" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3"><span class="header-section-number">3.6.3</span> Curva de convergencia del método ganador</h3>
<p><img src="assets/combinatoria/convergencia_ga.svg" alt="Convergencia del algoritmo genético" style="max-width: 100%; height: auto;"></p>
<p>Como apoyo adicional, también se dispone de una visualización estática del tour ganador, útil para inspeccionar la forma general del recorrido sin necesidad de reproducir la animación.</p>
</section>
</section>
</section>
<section id="conclusiones-y-aprendizajes" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusiones y Aprendizajes</h1>
<section id="conclusiones-generales" class="level2" data-number="4.1">
<h2 data-number="4.1"><span class="header-section-number">4.1</span> Conclusiones generales</h2>
<p>El trabajo permitió comparar dos familias de problemas de optimización con naturalezas muy distintas y dejó una conclusión central: la elección del método depende directamente de la estructura del problema. En la parte de optimización numérica, el descenso por gradiente mostró un buen comportamiento cuando la geometría de la función favorecía el uso de información local, como ocurrió especialmente en <code>Griewank</code>, <code>Six-Hump Camel</code> y, en menor medida, <code>Rosenbrock 2D</code>. Sin embargo, en funciones altamente multimodales o con paisajes más irregulares, como <code>Rastrigin</code>, <code>Schwefel</code> y <code>Goldstein-Price</code>, su desempeño se deterioró por la sensibilidad al punto inicial y la facilidad con la que puede quedar atrapado en mínimos locales.</p>
<p>La comparación final de la parte numérica confirmó que los métodos heurísticos ofrecieron la mejor calidad de solución en todos los casos analizados. Dentro de ellos, <code>Evolución diferencial</code> fue el método más robusto a nivel global, con el mejor resultado en <code>7 de 10</code> casos, mientras que <code>PSO</code> destacó especialmente en <code>Griewank</code> y <code>Six-Hump Camel</code>. Aun así, el descenso por gradiente conservó una ventaja importante en eficiencia computacional, ya que fue el método con menor número de evaluaciones en <code>7 de 10</code> casos. Esto muestra un patrón claro: los métodos locales pueden ser más baratos, pero los heurísticos y metaheurísticos son mucho más sólidos cuando la dificultad del paisaje aumenta.</p>
<p>En la parte de optimización combinatoria, el TSP sobre las <code>96</code> capitales departamentales de Francia evidenció que, en espacios discretos de gran tamaño, los enfoques exactos dejan de ser prácticos y las metaheurísticas se convierten en la alternativa más razonable. Tanto <code>ACO</code> como <code>GA</code> encontraron recorridos competitivos, pero el algoritmo genético alcanzó el mejor costo final con <code>3975.266333</code> euros, superando a <code>ACO</code>, que obtuvo <code>4022.039333</code> euros. La mejora fue de <code>46.773000</code> euros, equivalente a <code>1.1629 %</code>, lo que confirma que ambos métodos fueron competitivos, pero que <code>GA</code> tuvo una mayor capacidad de refinamiento sobre la solución final.</p>
<p>Un hallazgo especialmente valioso fue la complementariedad entre métodos. En la parte combinatoria, <code>ACO</code> mostró una muy buena capacidad para construir rápidamente una solución inicial de alta calidad, mientras que <code>GA</code> resultó más fuerte en la fase de mejora fina. Esta lógica de exploración seguida de refinamiento resume uno de los aprendizajes más importantes del proyecto: en problemas complejos, combinar estrategias puede ser más efectivo que depender de un único enfoque desde el inicio.</p>
</section>
<section id="aprendizajes-metodológicos" class="level2" data-number="4.2">
<h2 data-number="4.2"><span class="header-section-number">4.2</span> Aprendizajes metodológicos</h2>
<p>Otro resultado transversal del trabajo es que el éxito de la optimización no depende solo del algoritmo, sino también de cómo se formula el problema. En la parte combinatoria, la construcción del grafo, el <code>web scraping</code> de trayectos reales y la generación de una matriz completa de costos mínimos mediante <code>Dijkstra</code> fueron pasos tan importantes como la elección de <code>ACO</code> o <code>GA</code>. De forma análoga, en la parte numérica, la interpretación de la geometría de cada función fue clave para entender por qué algunos métodos convergían con estabilidad y otros no.</p>
<p>En conjunto, el proyecto confirma que no existe un método universalmente superior para todos los escenarios. Los métodos clásicos, como el descenso por gradiente, son apropiados cuando la función es diferenciable, el paisaje es relativamente favorable y se busca una solución rápida con bajo costo computacional. En cambio, los métodos heurísticos y metaheurísticos son preferibles cuando el problema es multimodal, la dimensión crece, el espacio de búsqueda es discreto o la información local ya no basta para orientar la búsqueda.</p>
<p>Como conclusión final, el trabajo muestra que optimizar no consiste en aplicar siempre el mismo algoritmo, sino en seleccionar o combinar herramientas según la dificultad, la representación y los objetivos del problema. Esa fue la lección más importante tanto en la parte numérica como en la combinatoria: la calidad de la solución depende de la correspondencia entre el método elegido y la naturaleza real del problema que se quiere resolver.</p>
</section>
</section>
<section id="parte-4-uso-de-inteligencia-artificial-en-el-proyecto" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Parte 4: Uso de Inteligencia Artificial en el Proyecto</h1>
<section id="prompts-principales-utilizados" class="level2" data-number="5.1">
<h2 data-number="5.1"><span class="header-section-number">5.1</span> 4.1 Prompts principales utilizados</h2>
<p>Los prompts reportados en esta seccion son una reconstruccion fiel de los usos principales que tuvo la IA durante el proyecto. No buscan ser una transcripcion literal de cada chat, sino resumir de forma clara las solicitudes que realmente influyeron en la implementacion, el analisis de resultados y la presentacion final del trabajo.</p>
<section id="prompt-1-diseno-de-experimentos-para-aco-y-ga" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1"><span class="header-section-number">5.1.1</span> Prompt 1: diseno de experimentos para ACO y GA</h3>
<pre class="text"><code>Estoy comparando colonia de hormigas y algoritmo genetico para el TSP de las capitales departamentales de Francia. Ayudame a decidir que hiperparametros vale la pena experimentar en cada metodo y a escribir el codigo para correr esos barridos, guardar resultados y graficar la convergencia.</code></pre>
<p><strong>Impacto en el resultado final.</strong> Este tipo de prompt permitio estructurar de manera mas rapida los experimentos de <code>mutation_rate</code>, <code>population_size</code> e <code>inject_aco_seed</code> en <code>GA</code>, y de <code>ants</code>, <code>beta</code> y <code>evaporation_rate</code> en <code>ACO</code>. Gracias a ello se pudieron comparar configuraciones reales en vez de dejar la seleccion de parametros a prueba y error informal.</p>
</section>
<section id="prompt-2-interpretacion-de-curvas-y-seleccion-de-configuracion-final" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2"><span class="header-section-number">5.1.2</span> Prompt 2: interpretacion de curvas y seleccion de configuracion final</h3>
<pre class="text"><code>Ya tengo las graficas y tablas de los experimentos de ACO y GA. Ayudame a interpretarlas y a escoger una configuracion balanceada, explicando que parametros mejoran el costo final, cuales aceleran la convergencia y cuales solo aumentan el costo computacional.</code></pre>
<p><strong>Impacto en el resultado final.</strong> La IA se uso como apoyo para leer las curvas de convergencia y justificar mejor la eleccion final de configuraciones. En particular, ayudo a identificar el efecto positivo de <code>inject_aco_seed</code>, el papel de <code>mutation_rate</code> en la velocidad de refinamiento de <code>GA</code> y el compromiso entre calidad y costo computacional en <code>ACO</code>.</p>
</section>
<section id="prompt-3-visualizacion-de-la-mejor-ruta-sobre-el-mapa-de-francia" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3"><span class="header-section-number">5.1.3</span> Prompt 3: visualizacion de la mejor ruta sobre el mapa de Francia</h3>
<pre class="text"><code>Quiero mostrar la mejor ruta final sobre un mapa de Francia dentro del notebook y no solo como un SVG estilizado. Ayudame a construir una visualizacion con folium o plotly, exportarla para el reporte y dejarla lista para incrustarla junto con la curva de convergencia.</code></pre>
<p><strong>Impacto en el resultado final.</strong> Este prompt mejoro de forma directa la calidad de la presentacion. La mejor solucion ya no quedo solo como una polilinea abstracta, sino como una ruta visible sobre un mapa, lo que hace mucho mas clara la interpretacion geografica del recorrido final y fortalece la calidad del reporte.</p>
</section>
<section id="prompt-4-integracion-de-tablas-figuras-y-texto-en-el-reporte-tecnico" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4"><span class="header-section-number">5.1.4</span> Prompt 4: integracion de tablas, figuras y texto en el reporte tecnico</h3>
<pre class="text"><code>Ayudame a convertir los resultados de los notebooks en una seccion de reporte tecnico en Quarto. Quiero una tabla comparativa final entre metodos, una explicacion breve de la convergencia y una redaccion clara de los hallazgos mas importantes.</code></pre>
<p><strong>Impacto en el resultado final.</strong> La IA ayudo a pasar de resultados dispersos en notebooks a una narrativa tecnica mas ordenada. Esto facilito integrar tablas, figuras y conclusiones en un formato consistente para el informe final, especialmente en la comparacion entre metodos y en la lectura de la convergencia.</p>
</section>
<section id="prompt-5-organizacion-e-interpretacion-de-resultados-en-optimizacion-numerica" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5"><span class="header-section-number">5.1.5</span> Prompt 5: organizacion e interpretacion de resultados en optimizacion numerica</h3>
<pre class="text"><code>Necesito resumir los resultados de descenso por gradiente y de los metodos heuristicos en tablas y figuras comparables. Ayudame a insertar las tablas reales, escoger visualizaciones utiles e interpretar que se observa en terminos de calidad de solucion, estabilidad y numero de evaluaciones.</code></pre>
<p><strong>Impacto en el resultado final.</strong> Este tipo de prompt sirvio para mejorar la lectura comparativa en la parte numerica. La IA ayudo a seleccionar que figuras eran mas utiles, como presentar los histogramas y como traducir los resultados cuantitativos en una discusion mas clara sobre robustez, multimodalidad y costo computacional.</p>
</section>
<section id="prompt-6-redaccion-de-introducciones-metodologia-y-cierre" class="level3" data-number="5.1.6">
<h3 data-number="5.1.6"><span class="header-section-number">5.1.6</span> Prompt 6: redaccion de introducciones, metodologia y cierre</h3>
<pre class="text"><code>Ayudame a redactar una introduccion breve, la metodologia y las conclusiones de un reporte academico sobre optimizacion numerica y combinatoria, manteniendo un tono tecnico y conectando bien los resultados con la discusion final.</code></pre>
<p><strong>Impacto en el resultado final.</strong> La IA se uso como apoyo de escritura tecnica para ordenar el documento y reducir tiempo de redaccion. Esto no sustituyo el analisis propio, pero si ayudo a que el informe final tuviera una estructura mas coherente y una mejor transicion entre problema, metodologia, resultados y conclusiones.</p>
</section>
</section>
<section id="impacto-global-de-la-ia-en-el-proyecto" class="level2" data-number="5.2">
<h2 data-number="5.2"><span class="header-section-number">5.2</span> 4.2 Impacto global de la IA en el proyecto</h2>
<p>En conjunto, la IA tuvo cuatro aportes principales dentro del trabajo. Primero, acelero la implementacion y depuracion de codigo para experimentos y visualizaciones. Segundo, ayudo a disenar mejor los barridos de parametros y a interpretar las curvas de convergencia, lo que tuvo impacto directo en la seleccion de configuraciones para <code>ACO</code> y <code>GA</code>. Tercero, mejoro la presentacion de resultados, especialmente en la ruta final sobre el mapa y en la organizacion de tablas y figuras. Cuarto, sirvio como apoyo para estructurar el reporte tecnico y redactar secciones de forma mas clara.</p>
<p>Por tanto, el uso de IA no consistio en delegar automaticamente la solucion del trabajo, sino en utilizarla como herramienta de apoyo para programacion, analisis y escritura tecnica. Las decisiones finales, la ejecucion de los experimentos, la seleccion de configuraciones y la revision del contenido quedaron bajo control del desarrollo realizado en el proyecto.</p>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyLXRpdGxl">Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXItdGl0bGU=">Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uZXh0">Parte 4: Uso de Inteligencia Artificial en el Proyecto</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1wcmV2">Optimización combinatoria</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOi9pbmRleC5odG1sSW50cm9kdWNjaW9u">Introduccion</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOi9udW1lcmljYS5odG1sT3B0aW1pemFjacOzbi1OdW3DqXJpY2E=">Optimización Numérica</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOi9jb21iaW5hdG9yaWEuaHRtbE9wdGltaXphY2nDs24tY29tYmluYXRvcmlh">Optimización combinatoria</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOi9yZXBvcnRlX3RlY25pY28uaHRtbFJlcG9ydGUtdGVjbmljby0tLVRyYWJham8tMDE=">Reporte tecnico - Trabajo 01</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOi9wcm9tcHRzLmh0bWxQYXJ0ZS00Oi1Vc28tZGUtSW50ZWxpZ2VuY2lhLUFydGlmaWNpYWwtZW4tZWwtUHJveWVjdG8=">Parte 4: Uso de Inteligencia Artificial en el Proyecto</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6SW5pY2lvbw==">Inicioo</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2luZGV4Lmh0bWw=">/index.html</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6TnVtZXJpY2E=">Numerica</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L251bWVyaWNhLmh0bWw=">/numerica.html</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6Q29tYmluYXRvcmlh">Combinatoria</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2NvbWJpbmF0b3JpYS5odG1s">/combinatoria.html</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6Q29uY2x1c2lvbmVz">Conclusiones</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2NvbmNsdXNpb25lcy5xbWQ=">/conclusiones.qmd</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6VXNvIGRlIElB">Uso de IA</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L3Byb21wdHMuaHRtbA==">/prompts.html</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWJyZWFkY3J1bWJzLVJlcG9ydGUtdGVjbmljby0tLVRyYWJham8tMDE=">Reporte tecnico - Trabajo 01</span></p>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGF0aXRsZQ==">Reporte tecnico - Trabajo 01 – Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkdGl0bGU=">Reporte tecnico - Trabajo 01 – Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZHRpdGxl">Reporte tecnico - Trabajo 01 – Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGFzaXRlbmFtZQ==">Trabajo Carlos</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkZGVzYw==">Optimizacion numerica y combinatoria</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZGRkZXNj">Optimizacion numerica y combinatoria</span></p>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-applegate2006" class="csl-entry" role="listitem">
Applegate, David L., Robert E. Bixby, Vasek Chvatal, and William J. Cook. 2006. <em>The Traveling Salesman Problem: A Computational Study</em>. Princeton University Press.
</div>
<div id="ref-dijkstra1959" class="csl-entry" role="listitem">
Dijkstra, E. W. 1959. <span>“A Note on Two Problems in Connexion with Graphs.”</span> <em>Numerische Mathematik</em> 1: 269–71. <a href="https://doi.org/10.1007/BF01386390">https://doi.org/10.1007/BF01386390</a>.
</div>
<div id="ref-jamil2013" class="csl-entry" role="listitem">
Jamil, Momin, and Xin-She Yang. 2013. <span>“A Literature Survey of Benchmark Functions for Global Optimisation Problems.”</span> <em>International Journal of Mathematical Modelling and Numerical Optimisation</em> 4 (2): 150–94. <a href="https://doi.org/10.1504/IJMMNO.2013.055204">https://doi.org/10.1504/IJMMNO.2013.055204</a>.
</div>
<div id="ref-nocedal2006" class="csl-entry" role="listitem">
Nocedal, Jorge, and Stephen J. Wright. 2006. <em>Numerical Optimization</em>. 2nd ed. Springer. <a href="https://doi.org/10.1007/978-0-387-40065-5">https://doi.org/10.1007/978-0-387-40065-5</a>.
</div>
<div id="ref-storn1997" class="csl-entry" role="listitem">
Storn, Rainer, and Kenneth Price. 1997. <span>“Differential Evolution – a Simple and Efficient Heuristic for Global Optimization over Continuous Spaces.”</span> <em>Journal of Global Optimization</em> 11 (4): 341–59. <a href="https://doi.org/10.1023/A:1008202821328">https://doi.org/10.1023/A:1008202821328</a>.
</div>
<div id="ref-talbi2009" class="csl-entry" role="listitem">
Talbi, El-Ghazali. 2009. <em>Metaheuristics: From Design to Implementation</em>. John Wiley &amp; Sons. <a href="https://doi.org/10.1002/9780470496916">https://doi.org/10.1002/9780470496916</a>.
</div>
<div id="ref-vinci2026" class="csl-entry" role="listitem">
VINCI Autoroutes. 2026. <em>Mon Trajet</em>. <a href="https://www.vinci-autoroutes.com/fr/mon-trajet/">https://www.vinci-autoroutes.com/fr/mon-trajet/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->

</body>

</html>
