<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Optimizacion combinatoria – Trabajo Carlos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4e663f3a4ff1a491e18bd6a28adf0390.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Trabajo Carlos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Inicioo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./numerica.html"> 
<span class="menu-text">Numerica</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./combinatoria.html"> 
<span class="menu-text">Combinatoria</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reporte_tecnico.html"> 
<span class="menu-text">Reporte Tecnico</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./combinatoria.html">Optimizacion combinatoria</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduccion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimización Numérica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./combinatoria.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Optimizacion combinatoria</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reporte_tecnico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reporte tecnico - Trabajo 01</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#parte-2-optimizacion-combinatoria-tsp---96-departamentos-de-francia" id="toc-parte-2-optimizacion-combinatoria-tsp---96-departamentos-de-francia" class="nav-link active" data-scroll-target="#parte-2-optimizacion-combinatoria-tsp---96-departamentos-de-francia">Parte 2: Optimizacion Combinatoria (TSP - 96 Departamentos de Francia)</a>
  <ul class="collapse">
  <li><a href="#descripcion-del-problema" id="toc-descripcion-del-problema" class="nav-link" data-scroll-target="#descripcion-del-problema">3.1 Descripcion del problema</a></li>
  <li><a href="#construccion-y-preprocesamiento-de-datos" id="toc-construccion-y-preprocesamiento-de-datos" class="nav-link" data-scroll-target="#construccion-y-preprocesamiento-de-datos">3.2 Construccion y preprocesamiento de datos</a></li>
  <li><a href="#algoritmos-utilizados" id="toc-algoritmos-utilizados" class="nav-link" data-scroll-target="#algoritmos-utilizados">3.3 Algoritmos utilizados</a>
  <ul class="collapse">
  <li><a href="#colonia-de-hormigas-aco" id="toc-colonia-de-hormigas-aco" class="nav-link" data-scroll-target="#colonia-de-hormigas-aco">Colonia de Hormigas (ACO)</a></li>
  <li><a href="#algoritmos-geneticos-ga" id="toc-algoritmos-geneticos-ga" class="nav-link" data-scroll-target="#algoritmos-geneticos-ga">Algoritmos Geneticos (GA)</a></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">3.4 Resultados</a></li>
  <li><a href="#visualizacion" id="toc-visualizacion" class="nav-link" data-scroll-target="#visualizacion">3.5 Visualizacion</a>
  <ul class="collapse">
  <li><a href="#comparacion-visual-de-costos" id="toc-comparacion-visual-de-costos" class="nav-link" data-scroll-target="#comparacion-visual-de-costos">Comparacion visual de costos</a></li>
  <li><a href="#gif-del-mejor-recorrido-en-francia" id="toc-gif-del-mejor-recorrido-en-francia" class="nav-link" data-scroll-target="#gif-del-mejor-recorrido-en-francia">GIF del mejor recorrido en Francia</a></li>
  <li><a href="#curva-de-convergencia-del-metodo-ganador" id="toc-curva-de-convergencia-del-metodo-ganador" class="nav-link" data-scroll-target="#curva-de-convergencia-del-metodo-ganador">Curva de convergencia del metodo ganador</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Optimizacion combinatoria</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="parte-2-optimizacion-combinatoria-tsp---96-departamentos-de-francia" class="level1">
<h1>Parte 2: Optimizacion Combinatoria (TSP - 96 Departamentos de Francia)</h1>
<section id="descripcion-del-problema" class="level2">
<h2 class="anchored" data-anchor-id="descripcion-del-problema">3.1 Descripcion del problema</h2>
<p>En la segunda parte del trabajo se aborda una variante del <strong>Problema del Viajante (TSP)</strong> aplicada al recorrido de las <strong>96 capitales departamentales de Francia metropolitana</strong>. El objetivo consiste en encontrar un orden de visita para todas las ciudades tal que se minimice el costo total del recorrido, cumpliendo la condicion clasica del TSP: cada ciudad debe visitarse exactamente una vez y, al finalizar, se debe completar el circuito regresando al punto de partida o cerrando la gira definida para la evaluacion. Debido a que el numero de rutas posibles crece de forma factorial con respecto al numero de ciudades, se trata de un problema combinatorio de muy alta complejidad, para el cual resulta poco practico aplicar metodos exactos en tiempos razonables.</p>
<p>En este contexto, cada solucion candidata puede representarse como una permutacion de las 96 ciudades, donde el orden de los elementos define la ruta seguida por el vendedor. Sin embargo, la evaluacion de esa ruta no se realiza directamente sobre el grafo parcial original, sino sobre una matriz completa de costos minimos entre todas las parejas de ciudades. De esta manera, el problema no se limita a encontrar la ruta mas corta en kilometros, sino la ruta de <strong>menor costo total</strong>, incorporando factores operativos mas cercanos a una situacion real de desplazamiento y dejando la instancia lista para ser tratada como un TSP clasico.</p>
<p>La funcion objetivo utilizada en la implementacion combina directamente tres componentes por tramo: <strong>peajes</strong>, <strong>gasolina</strong> y <strong>costo del tiempo del vendedor</strong>. En particular, el componente de combustible no se estima como distancia por costo por kilometro, sino que se toma directamente de la columna <code>gasolina(euros)</code> recuperada del dataset. A esto se suma el costo temporal del vendedor, calculado a partir del tiempo de viaje y una tarifa fija de <strong>12.02 EUR/h</strong>. En forma compacta, la expresion empleada es:</p>
<p><span class="math display">\[
\text{Costo total} = \text{peajes(euros)} + \text{gasolina(euros)} + \left(\frac{\text{tiempo(min)}}{60}\right)\times 12.02
\]</span></p>
<p>Bajo esta formulacion, el costo total de un tour se obtiene acumulando ese valor sobre los tramos recorridos en la ruta. Esto hace que el problema sea especialmente adecuado para el uso de metaheuristicas, ya que el reto consiste en explorar un espacio enorme de posibles recorridos y encontrar una secuencia que balancee de manera eficiente tiempo y costo monetario en una red vial real.</p>
</section>
<section id="construccion-y-preprocesamiento-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="construccion-y-preprocesamiento-de-datos">3.2 Construccion y preprocesamiento de datos</h2>
<p>La construccion del conjunto de datos para esta parte del trabajo se realizo en varias etapas. Primero, se extrajeron las coordenadas geograficas de las ciudades desde el sitio web <a href="https://geokeo.com/database/town/fr/23/">GeoKeo</a>, tomando como referencia las capitales departamentales de Francia. A partir de estas coordenadas se genero una primera estructura de conexiones entre ciudades cercanas, utilizada como base para construir un grafo inicial de rutas, el cual fue exportado a un archivo CSV para facilitar su revision posterior.</p>
<p>Posteriormente, este grafo fue ajustado y validado manualmente con apoyo de visualizaciones sobre mapa, con el fin de identificar conexiones plausibles dentro de la red y corregir aquellas que no representaban trayectos razonables. Esta etapa fue importante porque la cercania geografica por si sola no garantiza que dos ciudades esten conectadas por una ruta real o conveniente dentro de la red vial.</p>
<p>Una vez consolidada esta red base, se realizo el proceso de <code>web scraping</code> sobre el sitio <a href="https://www.vinci-autoroutes.com/fr/mon-trajet/">VINCI Autoroutes</a>, utilizando las rutas previamente definidas para consultar y completar informacion real de los trayectos. En particular, para cada conexion se obtuvo la distancia recorrida, el tiempo estimado de viaje y el valor de los peajes. Para mantener consistencia en la recoleccion de la informacion, en VINCI Autoroutes se utilizo la categoria <strong>Clase 1 - Vehiculos ligeros</strong>, correspondiente a automoviles particulares y vehiculos de uso ligero. Estos datos sirvieron como base para estructurar el conjunto final utilizado en la optimizacion combinatoria.</p>
<p>Como paso previo a la optimizacion, se ejecuto <strong>Dijkstra desde cada ciudad</strong> sobre el grafo ponderado de conexiones directas para construir una matriz completa de costos minimos entre todas las parejas de nodos. Este cierre sobre el grafo fue el puente metodologico que permitio pasar de una red vial parcial a una instancia TSP de <code>96 x 96</code>, de modo que ACO y GA no optimizan sobre el grafo original, sino sobre la matriz consolidada resultante. Sobre esa matriz se verifico que la estructura fuera cuadrada, que la diagonal quedara en cero y que no existieran valores infinitos fuera de la diagonal, asegurando asi que ambos metodos pudieran trabajar sobre una representacion consistente del problema.</p>
<p><a href="./notebooks/combinatoria/00_construccion_grafo_inicial.html" class="notebook-card-link"> <span class="notebook-card-icon"> <svg width="24" height="24" viewbox="0 0 64 64" fill="none" aria-hidden="true"> <ellipse cx="32" cy="32" rx="17" ry="10.5" stroke="#f37726" stroke-width="4.5"></ellipse> <circle cx="50.5" cy="21" r="3.2" fill="#9e9e9e"></circle> <circle cx="13.5" cy="43" r="3.2" fill="#9e9e9e"></circle> </svg> </span> <span class="notebook-card-title">Cuaderno de construccion inicial del grafo</span> </a></p>
</section>
<section id="algoritmos-utilizados" class="level2">
<h2 class="anchored" data-anchor-id="algoritmos-utilizados">3.3 Algoritmos utilizados</h2>
<p>Para resolver este problema se emplearon dos metaheuristicas clasicas para optimizacion combinatoria: <strong>Colonia de Hormigas (ACO)</strong> y <strong>Algoritmos Geneticos (GA)</strong>. La eleccion de estos metodos responde a que ambos estan diseniados para explorar espacios de busqueda discretos muy grandes y han mostrado buen desempeno en variantes del TSP. Ademas, permiten balancear de manera flexible los procesos de exploracion y explotacion, lo cual es importante cuando se busca escapar de soluciones pobres sin perder la capacidad de refinar rutas prometedoras.</p>
<section id="colonia-de-hormigas-aco" class="level3">
<h3 class="anchored" data-anchor-id="colonia-de-hormigas-aco">Colonia de Hormigas (ACO)</h3>
<p>El algoritmo de colonia de hormigas construye soluciones de manera progresiva, simulando el comportamiento colectivo de hormigas que depositan feromonas sobre los caminos recorridos. En cada iteracion, varias hormigas generan rutas completas entre las ciudades, eligiendo el siguiente nodo con base en una combinacion entre la <strong>feromona acumulada</strong> y una <strong>heuristica local</strong> asociada al inverso del costo entre ciudades. Con el paso de las iteraciones, las rutas de menor costo reciben mayor refuerzo y tienden a guiar la busqueda hacia regiones mas prometedoras del espacio de soluciones.</p>
<p>En la implementacion utilizada se fijaron los siguientes parametros:</p>
<ul>
<li>numero de hormigas: <code>40</code></li>
<li>numero de iteraciones: <code>250</code></li>
<li>importancia de la feromona (<code>alpha</code>): <code>1.0</code></li>
<li>importancia de la heuristica (<code>beta</code>): <code>3.0</code></li>
<li>tasa de evaporacion: <code>0.35</code></li>
<li>factor de intensificacion: <code>2.0</code></li>
<li>peso elitista para reforzar la mejor ruta global: <code>2.0</code></li>
<li>semilla aleatoria: <code>42</code></li>
</ul>
<p>Estos valores permiten dar mayor peso a la informacion heuristica del costo entre ciudades, sin eliminar la influencia del aprendizaje colectivo por feromonas. La evaporacion evita que la busqueda se estanque demasiado pronto en rutas suboptimas, mientras que el refuerzo elitista ayuda a conservar y explotar la mejor solucion global encontrada hasta cada iteracion.</p>
</section>
<section id="algoritmos-geneticos-ga" class="level3">
<h3 class="anchored" data-anchor-id="algoritmos-geneticos-ga">Algoritmos Geneticos (GA)</h3>
<p>El algoritmo genetico aborda el problema manteniendo una <strong>poblacion de rutas candidatas</strong> que evoluciona a lo largo de varias generaciones. Cada individuo representa un recorrido completo por las ciudades, y su aptitud se evalua con el costo total de la ruta. A partir de esta evaluacion, se seleccionan las mejores soluciones para producir descendencia mediante operadores de cruce y mutacion. De este modo, el metodo combina informacion de rutas de buena calidad y genera nuevas alternativas que pueden mejorar progresivamente el resultado obtenido.</p>
<p>En este trabajo, el GA se implemento con una estrategia de <strong>seleccion por torneo</strong>, <strong>cruce ordenado</strong> y <strong>mutacion por intercambio</strong> de posiciones dentro de la ruta. Ademas, se permitio inyectar como semilla inicial la mejor ruta producida por ACO, con el fin de aprovechar una buena solucion de partida y refinarla en una fase evolutiva posterior.</p>
<p>Los parametros usados fueron:</p>
<ul>
<li>tamano de poblacion: <code>180</code></li>
<li>numero de generaciones: <code>350</code></li>
<li>tasa de mutacion: <code>0.12</code></li>
<li>tasa de cruce: <code>0.9</code></li>
<li>numero de individuos elitistas preservados por generacion: <code>12</code></li>
<li>tamano del torneo de seleccion: <code>5</code></li>
<li>uso de semilla inicial proveniente de ACO: <code>True</code></li>
<li>semilla aleatoria: <code>42</code></li>
</ul>
<p>La justificacion de esta configuracion es que una poblacion relativamente amplia favorece la diversidad de soluciones, mientras que una tasa de cruce alta promueve la recombinacion de rutas prometedoras. La mutacion moderada introduce variacion sin destruir excesivamente las estructuras utiles encontradas, y el elitismo garantiza que las mejores soluciones no se pierdan entre generaciones.</p>
<p>En conjunto, ACO y GA ofrecen dos perspectivas complementarias sobre el mismo problema. ACO destaca por su capacidad para construir soluciones guiadas por memoria colectiva y heuristicas locales, mientras que GA resulta util para recombinar y refinar soluciones ya competitivas dentro de una poblacion diversa. Esta combinacion permite comparar estrategias de busqueda distintas e incluso aprovechar la salida de un metodo como punto de partida para el otro.</p>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">3.4 Resultados</h2>
<p>Los experimentos realizados sobre la instancia de las 96 capitales departamentales muestran que ambos metodos fueron capaces de producir recorridos validos y de costo competitivo. Sin embargo, el mejor resultado final fue alcanzado por el <strong>algoritmo genetico (GA)</strong>, que logro refinar la solucion inicial y obtener un costo total inferior al conseguido por la colonia de hormigas.</p>
<p>La comparacion final entre metodos puede resumirse en la siguiente tabla:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Metodo</th>
<th style="text-align: right;">Mejor costo del tour (EUR)</th>
<th style="text-align: right;">Diferencia frente al mejor (EUR)</th>
<th style="text-align: right;">Iteraciones / generaciones</th>
<th style="text-align: right;">Tamano de busqueda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GA</td>
<td style="text-align: right;">4303.602999</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">350</td>
<td style="text-align: right;">180</td>
</tr>
<tr class="even">
<td>ACO</td>
<td style="text-align: right;">4471.569332</td>
<td style="text-align: right;">167.966333</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">40</td>
</tr>
</tbody>
</table>
<p>El <strong>costo total optimo encontrado</strong> fue de <strong>4303.602999 euros</strong>, calculado con la funcion de costo definida a partir de peajes, combustible y tiempo del vendedor. Este resultado se obtuvo usando como vehiculo de referencia un <strong>Renault Clio</strong>, con combustible tipo gasolina, y una tarifa del vendedor de <strong>12.02 euros por hora</strong>, de acuerdo con la formulacion del modelo.</p>
<p>En cuanto a la comparacion entre metodos, ACO alcanzo un mejor costo de <strong>4471.569332 euros</strong>, mientras que GA obtuvo <strong>4303.602999 euros</strong>. En otras palabras, <strong>GA mejoro a ACO en 167.966333 euros, equivalente a una mejora relativa de 3.7563 %</strong>. Este comportamiento sugiere que ACO fue efectivo para construir una buena ruta inicial, pero que GA tuvo una mayor capacidad de refinamiento al recombinar y ajustar soluciones candidatas a lo largo de las generaciones.</p>
<p>Desde el punto de vista de la convergencia, esta dinamica resulta especialmente interesante: ACO encuentra rapidamente una solucion base competitiva para una instancia grande del TSP, mientras que GA aprovecha esa referencia inicial y la sigue refinando hasta obtener una mejora final del <strong>3.7563 %</strong>. Esto refuerza la idea de que ambos metodos no solo compiten entre si, sino que tambien pueden complementarse dentro del flujo de optimizacion.</p>
<p>La <strong>mejor ruta encontrada</strong> puede leerse de forma mas clara si se resume por tramos geograficos:</p>
<ul>
<li>inicio y arco mediterraneo: <code>Bourg-en-Bresse -&gt; Gap -&gt; Ajaccio -&gt; Bastia -&gt; Nice -&gt; Digne-les-Bains -&gt; Toulon -&gt; Marseille -&gt; Avignon -&gt; Nimes -&gt; Montpellier -&gt; Perpignan</code></li>
<li>suroccidente y eje atlantico: <code>Carcassonne -&gt; Foix -&gt; Auch -&gt; Tarbes -&gt; Pau -&gt; Mont-de-Marsan -&gt; Bordeaux -&gt; Tours -&gt; Blois -&gt; Orleans -&gt; Chartres -&gt; Evreux -&gt; Cergy -&gt; Paris</code></li>
<li>region norte y noreste: <code>Creteil -&gt; Bobigny -&gt; Nanterre -&gt; Versailles -&gt; Evry-Courcouronnes -&gt; Melun -&gt; Auxerre -&gt; Troyes -&gt; Bar-le-Duc -&gt; Chaumont -&gt; Vesoul -&gt; Besancon -&gt; Belfort -&gt; Colmar -&gt; Strasbourg -&gt; Epinal -&gt; Nancy -&gt; Metz -&gt; Charleville-Mezieres -&gt; Chalons-en-Champagne -&gt; Laon -&gt; Lille -&gt; Arras -&gt; Amiens -&gt; Beauvais -&gt; Rouen</code></li>
<li>occidente y regreso al centro-este: <code>Saint-Lo -&gt; Caen -&gt; Alencon -&gt; Le Mans -&gt; Angers -&gt; Laval -&gt; Rennes -&gt; Saint-Brieuc -&gt; Quimper -&gt; Vannes -&gt; Nantes -&gt; La Roche-sur-Yon -&gt; La Rochelle -&gt; Niort -&gt; Poitiers -&gt; Angouleme -&gt; Perigueux -&gt; Agen -&gt; Cahors -&gt; Montauban -&gt; Toulouse -&gt; Albi -&gt; Rodez -&gt; Mende -&gt; Aurillac -&gt; Tulle -&gt; Limoges -&gt; Gueret -&gt; Chateauroux -&gt; Bourges -&gt; Nevers -&gt; Clermont-Ferrand -&gt; Moulins -&gt; Macon -&gt; Lons-le-Saunier -&gt; Dijon -&gt; Annecy -&gt; Chambery -&gt; Grenoble -&gt; Valence -&gt; Privas -&gt; Le Puy-en-Velay -&gt; Saint-Etienne -&gt; Lyon -&gt; Bourg-en-Bresse</code></li>
</ul>
<p>En terminos cualitativos, los resultados muestran una dinamica complementaria entre ambos enfoques. ACO aporta una exploracion guiada por informacion local y memoria colectiva, lo que permite encontrar rapidamente rutas razonables en un espacio de busqueda muy grande. Por su parte, GA aprovecha esa base inicial y la mejora mediante operadores evolutivos, conservando buenas estructuras parciales y corrigiendo tramos menos eficientes del recorrido. Por esta razon, dentro de los experimentos realizados, <strong>GA puede considerarse el metodo con mejor desempeno final</strong> para esta instancia del problema.</p>
</section>
<section id="visualizacion" class="level2">
<h2 class="anchored" data-anchor-id="visualizacion">3.5 Visualizacion</h2>
<p>La visualizacion final se realiza sobre el mapa de <strong>Francia</strong>, mostrando el recorrido ganador obtenido por el algoritmo genetico. El GIF permite observar la progresion espacial del tour, mientras que la curva de convergencia muestra como el costo va disminuyendo a medida que avanzan las generaciones del metodo ganador.</p>
<section id="comparacion-visual-de-costos" class="level3">
<h3 class="anchored" data-anchor-id="comparacion-visual-de-costos">Comparacion visual de costos</h3>
</section>
<section id="gif-del-mejor-recorrido-en-francia" class="level3">
<h3 class="anchored" data-anchor-id="gif-del-mejor-recorrido-en-francia">GIF del mejor recorrido en Francia</h3>
<p><img src="assets/combinatoria/mejor_solucion_combinatoria.gif" alt="GIF del mejor recorrido sobre Francia" style="max-width: 100%; height: auto;"></p>
</section>
<section id="curva-de-convergencia-del-metodo-ganador" class="level3">
<h3 class="anchored" data-anchor-id="curva-de-convergencia-del-metodo-ganador">Curva de convergencia del metodo ganador</h3>
<p><img src="assets/combinatoria/convergencia_ga.svg" alt="Convergencia del algoritmo genetico" style="max-width: 100%; height: auto;"></p>
<p>Como apoyo adicional, tambien se dispone de una visualizacion estatica del tour ganador, util para inspeccionar la forma general del recorrido sin necesidad de reproducir la animacion.</p>
<p><img src="assets/combinatoria/visualizacion_mejor_solucion.svg" alt="Visualizacion estatica de la mejor ruta" style="max-width: 100%; height: auto;"></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>